/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)

#define EXTERN extern
#include "GuiData.h"

static void EnglishInitButton(WM_HWIN hWin);
static void ChineseInitButton(WM_HWIN hWin);
static void RussianInitButton(WM_HWIN hWin);
static void _cbDialog(WM_MESSAGE * pMsg);
static void MenuDisp(int pos, int stat);
static void AcbMccbMenu(int nPos);
static void MlinkMenu(int nPos);

static WM_HWIN ButtonItem[AcbMccbMenuCount];

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
//extern uint8_t KeyStatus[5];
//extern uint16_t KeyPin[5];

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
static void EnglishInitButton(WM_HWIN hWin)
{
	WM_HWIN hItem;
	WINDOW_SetBkColor(hWin, GUI_MAKE_COLOR(COLOR_MAIN_BG));
	hItem = WM_GetDialogItem(hWin, ID_BUTTON_0);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmHWINFO_enable);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmHWINFO_Focus);
//	BUTTON_SetPressed(hItem, 1);
	ButtonItem[HW_SET] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_1);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_IOstatus_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_IOstatus_selected);
		ButtonItem[MEASUREMENT] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_measurement_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_measurement_selected);
		ButtonItem[MEASUREMENT] = hItem;
	}
	hItem = WM_GetDialogItem(hWin, ID_BUTTON_2);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_systeminfo_normal);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_systeminfo_selected);
	ButtonItem[INFO] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_3);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_IOset_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_IOset_selected);
		ButtonItem[RELAY_SET] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmRELAYINFO_enable);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmRELAYINFO_Focus);
		ButtonItem[RELAY_SET] = hItem;
	}

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_4);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_events_normal);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_events_selected);
	ButtonItem[EVENT] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_5);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmcontrol_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmcontrol_selected);
		ButtonItem[CONTROL] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmacbmccb_control_btn_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmacbmcc_control_btn_selected);
		ButtonItem[CONTROL] = hItem;
	}
}

static void ChineseInitButton(WM_HWIN hWin)
{
	WM_HWIN hItem;
	WINDOW_SetBkColor(hWin, GUI_MAKE_COLOR(COLOR_MAIN_BG));
	hItem = WM_GetDialogItem(hWin, ID_BUTTON_0);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_hwset_normal_ch);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_hwset_selected_ch);
//	BUTTON_SetPressed(hItem, 1);
	ButtonItem[HW_SET] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_1);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_IOstatus_normal_ch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_IOstatus_selected_ch);
		ButtonItem[MEASUREMENT] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_measurement_normal_ch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_measurement_selected_ch);
		ButtonItem[MEASUREMENT] = hItem;
	}
	hItem = WM_GetDialogItem(hWin, ID_BUTTON_2);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_systeminfo_normal_ch);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_systeminfo_selected_ch);
	ButtonItem[INFO] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_3);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_IOset_normal_ch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_IOset_selected_ch);
		ButtonItem[RELAY_SET] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_relayset_normal_ch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_relayset_selected_ch);
		ButtonItem[RELAY_SET] = hItem;
	}

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_4);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_events_normal_ch);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_events_selected_ch);
	ButtonItem[EVENT] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_5);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmcontrol_btn_normal_ch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmcontrol_btn_selected_ch);
		ButtonItem[CONTROL] = hItem;
	}
	else
	{

		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmacbmccb_control_normal_ch);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmacbmccb_control_selected_ch);
		ButtonItem[CONTROL] = hItem;
	}
}

static void RussianInitButton(WM_HWIN hWin)
{
	WM_HWIN hItem;
	WINDOW_SetBkColor(hWin, GUI_MAKE_COLOR(COLOR_MAIN_BG));
	hItem = WM_GetDialogItem(hWin, ID_BUTTON_0);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmHWINFO_enable);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmHWINFO_Focus);
//	BUTTON_SetPressed(hItem, 1);
	ButtonItem[HW_SET] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_1);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_IOstatus_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_IOstatus_selected);
		ButtonItem[MEASUREMENT] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_measurement_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_measurement_selected);
		ButtonItem[MEASUREMENT] = hItem;
	}
	hItem = WM_GetDialogItem(hWin, ID_BUTTON_2);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_systeminfo_normal);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_systeminfo_selected);
	ButtonItem[INFO] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_3);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_IOset_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_IOset_selected);
		ButtonItem[RELAY_SET] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmRELAYINFO_enable);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmRELAYINFO_Focus);
		ButtonItem[RELAY_SET] = hItem;
	}

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_4);
	(void)BUTTON_SetText(hItem, "");
	BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmbtn_events_normal);
	BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmbtn_events_selected);
	ButtonItem[EVENT] = hItem;

	hItem = WM_GetDialogItem(hWin, ID_BUTTON_5);
	(void)BUTTON_SetText(hItem, "");
	if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MLINK)
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmcontrol_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmcontrol_selected);
		ButtonItem[CONTROL] = hItem;
	}
	else
	{
		BUTTON_SetBitmap(hItem, BUTTON_BI_UNPRESSED, &bmacbmccb_control_btn_normal);
		BUTTON_SetBitmap(hItem, BUTTON_BI_PRESSED, &bmacbmcc_control_btn_selected);
		ButtonItem[CONTROL] = hItem;
	}
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
	// USER START (Optionally insert additional variables)
	// USER END

	switch (pMsg->MsgId)
	{
		case WM_INIT_DIALOG:
		{
			if(SettingValue[SETUP_LANGUAGE] == CHINESE)
			{
				ChineseInitButton(pMsg->hWin);
			}
			else
			if(SettingValue[SETUP_LANGUAGE] == RUSSIAN)
			{
				RussianInitButton(pMsg->hWin);
			}
			else
			{
				EnglishInitButton(pMsg->hWin);
			}
			MenuDisp(0, 1);
		// USER END
			break;
		}
		default:
		{
			WM_DefaultProc(pMsg);
			break;
		}
	}
}

static void MenuDisp(int pos, int stat)
{
//	for(int i = 0; i < AcbMccbMenuCount; i++)
//	{
//		int stat = 0;
//		if(i == pos)
//			stat = 1;
		BUTTON_SetPressed(ButtonItem[pos], stat);
//	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
static void AcbMccbMenu(int nPos)
{
	if(nPos == HW_SET)
	{
		AcbMccbHwSet();
	}
	else
	if(nPos == MEASUREMENT)
	{
		AcbMccbMeasurement();
	}
	else
	if(nPos == INFO)
	{
		AcbMccbInfomation();
	}
	else
	if(nPos == RELAY_SET)
	{
		AcbMccbRelaySet();
	}
	else
	if(nPos == EVENT)
	{
		AcbMccbEvent();
	}
	else
	if(nPos == CONTROL)
	{
		if(ConnectSetting[gDeviceIndex].DeviceType == DEVICE_MCCB || (ConnectSetting[gDeviceIndex].DeviceType == DEVICE_ACB && nTrio[gDeviceIndex] == INDEX_7))   // 111b: ACB OCR Only
		{
			StuMccbIo();
		}
		else
		{
			AcbMccbControl();
		}
	}
	else {}
}

static void MlinkMenu(int nPos)
{
	int flagBreak = FALSE;
	if(nPos == HW_SET)
	{
		MLinkHwSet();
	}
	else
	if(nPos == MEASUREMENT)
	{
		MLinkOverview();
		gCommOldStatus[gDeviceIndex] = -1;
		gStatusSendEnd = STATUS_SEND_ING;
		OverviewSend();
		while(1)
		{
			E_KEY key = GetKey();

			if(key == TIME_OUT)
			{
				gStatusSendEnd = STATUS_SEND_ING;
				nSendStep = 0;
				statusSendStep = 0;
				OverviewSend();
			}
			else
			if(key == KEY_SETUP)
			{
				if(Setup() == SETUP_CHANGED)
				{
					flagBreak = TRUE;
				}
				MLinkOverview();
			}
			else
			if(key == DATA_RECV)
			{
				if(gStatusSendEnd == STATUS_SEND_ING)
				{
					StatusRecv();
					OverviewSend();
				}
				else
				{
					if(nSendStep == 0)
					{
						OverViewValue(1);
						nSendStep = 1;
						OverviewSend();
					}
					else
					if(nSendStep == 1)
					{
						OverViewValue(1);
						nSendStep = 0;
						gStatusSendEnd = STATUS_SEND_ING;
					}
					else {}
				}
			}
			else
			if(key == KEY_CANCEL)
			{
				flagBreak = TRUE;
			}
			else
			if(key == KEY_COMM_ERROR)
			{
				(void)printf("COMM Error!! gStatusSendEnd=%d, statusSendStep=%d\n",gStatusSendEnd,statusSendStep);
				if(StatusRecvErrorProcess() == STATUS_SEND_ING)
				{
					nSendStep = 0;
				}
				else
				{
					gStatusSendEnd = STATUS_SEND_ING;
					statusSendStep = 0;
					nSendStep = 0;
					(void)StatusRecvErrorProcess();
				}
			}
			else
			if(key == COMM_STAT_ERROR)
			{
				MLinkOverview();
				gCommOldStatus[gDeviceIndex] = -1;
				gStatusSendEnd = STATUS_SEND_ING;
			}
			else {}

			if(flagBreak == TRUE)
			{
				break;
			}
		}
	}
	else
	if(nPos == INFO)
	{
		MLinkInfomation();
	}
	else
	if(nPos == RELAY_SET)
	{
		MLinkIOSet();
	}
	else
	if(nPos == EVENT)
	{
		MLinkEvent();
	}
	else
	if(nPos == CONTROL)
	{
		MLinkControl();
	}
	else {}
}


static void MainDlgSend(void)
{
	if(StatusSend() == STATUS_SEND_ING)
	{
		return;
	}
	ModbusSendFrame(ConnectSetting[gDeviceIndex].Address, INPUT_REGISTER, I_REGISTER_183, INDEX_1);	// 30183 ~ 30183
}


/*********************************************************************
*
*       CreateMenu
*/
// PRQA S 1503 1
WM_HWIN CreateMenu(E_DEVICE_TYPE DeviceType)
{
	int flagBreak = FALSE;
	WM_HWIN hWin;
	int nMainMenuPos = 0;
	static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
	{
// PRQA S 1334 ++
// PRQA S 3635 ++
		{ WINDOW_CreateIndirect, "AcbMccbMenu", ID_WINDOW_0, 0, 0, 480, 286, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "HWSet", ID_BUTTON_0, 10, 10, 150, 130, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "Measurement", ID_BUTTON_1, 165, 9, 150, 130, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "SystemInfo", ID_BUTTON_2, 320, 10, 150, 130, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "RelaySet", ID_BUTTON_3, 10, 145, 150, 130, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "Event", ID_BUTTON_4, 165, 146, 150, 130, 0, 0x0, 0 },
		{ BUTTON_CreateIndirect, "Control", ID_BUTTON_5, 320, 146, 150, 130, 0, 0x0, 0 },
// PRQA S 1334 --
// PRQA S 3635 --
		// USER START (Optionally insert additional widgets)
		// USER END
	};

	hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), &_cbDialog, WM_HBKWIN, 0, Y0_MAIN);

	ReadyToSend();
	MainDlgSend();
	uint16_t language;
	while (1)
	{
		E_KEY key = GetKey();

		if(key == TIME_OUT)
		{
			gStatusSendEnd = STATUS_SEND_ING;
			statusSendStep = 0;
			(void)StatusSend();
		}
		else
		if(key == KEY_SETUP)
		{
			WM_HideWindow(hWin);
			language = SettingValue[SETUP_LANGUAGE];
			if(Setup() == SETUP_CHANGED)
			{
				flagBreak = TRUE;
			}
			(void)printf("\n\n\n\n\n\n old=%d, new=%d\n\n\n\n\n\n", language,SettingValue[SETUP_LANGUAGE]);
			if(language != SettingValue[SETUP_LANGUAGE])
			{
				(void)printf("language changed!!!!\n");
				if(SettingValue[SETUP_LANGUAGE] == CHINESE)
				{
					ChineseInitButton(hWin);
				}
				else
				if(SettingValue[SETUP_LANGUAGE] == RUSSIAN)
				{
					RussianInitButton(hWin);
				}
				else
				{
					EnglishInitButton(hWin);
				}
			}
			WM_ShowWindow(hWin);
		}
		else
		if(key == KEY_UP)
		{
			MenuDisp(nMainMenuPos, 0);
			if(nMainMenuPos > 0)
			{
				nMainMenuPos--;
			}
			else
			{
				nMainMenuPos = AcbMccbMenuCount - 1;
			}
			MenuDisp(nMainMenuPos, 1);
		}
		else
		if(key == KEY_DOWN)
		{
			MenuDisp(nMainMenuPos, 0);
			if(nMainMenuPos < (AcbMccbMenuCount-1))
			{
				nMainMenuPos++;
			}
			else
			{
				nMainMenuPos = 0;
			}
			MenuDisp(nMainMenuPos, 1);
		}
		else
		if(key == KEY_ENTER)
		{
			WM_HideWindow(hWin);
			language = SettingValue[SETUP_LANGUAGE];
//			gStatusSendEnd = STATUS_SEND_ING;
//			statusSendStep = 0;
//			nSendStep = 0;
			ReadyToSend();
			if((DeviceType == DEVICE_ACB) || (DeviceType == DEVICE_MCCB))
			{
				AcbMccbMenu(nMainMenuPos);
			}
			else
			if(DeviceType == DEVICE_MLINK)
			{
				MlinkMenu(nMainMenuPos);
			}
			else {}
			(void)printf("InMainMenu.....\n");
			gCommOldStatus[gDeviceIndex] = -1;
			(void)printf("\n\n\n\n\n\n old=%d, new=%d\n\n\n\n\n\n", language,SettingValue[SETUP_LANGUAGE]);
			if(language != SettingValue[SETUP_LANGUAGE])
			{
				(void)printf("language changed!!!!\n");
				if(SettingValue[SETUP_LANGUAGE] == CHINESE)
				{
					ChineseInitButton(hWin);
				}
				else
				if(SettingValue[SETUP_LANGUAGE] == RUSSIAN)
				{
					RussianInitButton(hWin);
				}
				else
				{
					EnglishInitButton(hWin);
				}
			}
			ReadyToSend();
			gStatusSendEnd = STATUS_SEND_ING;
			statusSendStep = 0;
			nSendStep = 0;
			(void)StatusSend();
			WM_ShowWindow(hWin);
		}
		else
		if(key == DATA_RECV)
		{
			if(gStatusSendEnd == STATUS_SEND_ING)
			{
				StatusRecv();
				MainDlgSend();
			}
			else
			{
				nTrio[gDeviceIndex] = (ModbusGetUint16(I_REGISTER_183) >> CB_TRIO_SHIFT) & CB_TRIO_MASK;	// TRIO °á¼± 000b: TRIO Only 001b: TRIO+ACB_OCR 010b: TRIO+MCCB 111b: ACB OCR Only
				g_bRecvAllDone = TRUE;
				//(void)printf("g_bRecvAllDone=0\n");
			}
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else
		if(key == KEY_COMM_ERROR)
		{
			(void)printf("COMM Error!! gStatusSendEnd=%d, statusSendStep=%d\n",gStatusSendEnd,statusSendStep);
			if(StatusRecvErrorProcess() == STATUS_SEND_ING)
			{
				nSendStep = 0;
			}
			else
			{
				g_bRecvAllDone = TRUE;

				gStatusSendEnd = STATUS_SEND_ING;
				statusSendStep = 0;
//				StatusRecvErrorProcess();
			}
		}
		else {}

		if(flagBreak == TRUE)
		{
			break;
		}
	}

	(void)printf("\nExit\n");
	return hWin;
}

/*************************** End of file ****************************/
