/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#define EXTERN extern
#include "stm32f4xx_hal.h"
#include "main.h"
#include "GuiData.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
static void MLinkEventInitDisp(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// PRQA S 1505 1
void CountDisp(int total, int index)
{
	char buf[DEFAULT_BUF_SIZE];
	(void)sprintf(buf, "%d/%d", index, total);

	(void)printf("\n\n\n\n\n\ntotal=%d, cur=%d\n",total,  index);

	GUI_SetColor(COLOR_VALUE);
	(void)GUI_SetFont(&GUI_Font20B_ASCII);
	GUI_SetBkColor(COLOR_MAIN_BG);
	GUI_RECT rect;
	rect.x0 = MLINK_EVENT_INDEX_X0;
	rect.y0 = EVENT_TITLE_Y0;
	rect.x1 = EVENT_INDEX_X1;
	rect.y1 = EVENT_TITLE_Y1;
	GUI_ClearRectEx(&rect);
	GUI_DispStringInRect(buf, &rect, GUI_TA_RIGHT | GUI_TA_BOTTOM);

}

static void MLinkEventInitDisp(void)
{
	GUI_SetBkColor(COLOR_MAIN_BG);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_LINE);

	GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);
	GUI_DrawRect(STARTX_CONTENTS, EVENT_CONTENTS_Y0, (STARTX_CONTENTS + WIDTH_CONTENTS) - 1, EVENT_CONTENTS_Y1);


	(void)printf("\n\n\n\n\n\ntotal=%d, cur=%d\n",nEventTotal,  nCurrIndex);
	if(gCommStatus[gDeviceIndex] == COMM_OK)
	{
		if(nEventTotal == 0)
		{
			nCurrIndex = 0;
		}
		CountDisp(nEventTotal, nCurrIndex);
	}

	GUI_SetColor(COLOR_LABEL);
	GUI_RECT rect;
	rect.x0 = EVENT_X0;
	rect.y0 = EVENT_TITLE_Y0;
	rect.x1 = EVENT_TITLE_X1;
	rect.y1 = EVENT_TITLE_Y1;
	(void)GUI_SetFont(&GUI_Font24_ASCII);
	GUI_DispStringInRect("Event", &rect, GUI_TA_LEFT | GUI_TA_VCENTER);


//	if((gCommStatus[gDeviceIndex] == COMM_OK) && (nEventTotal == 0))
//	{
//		LanguageSelect(FONT24B);
//		GUI_SetColor(COLOR_VALUE);
//		rect.x0 = EVENT_X0;
//		rect.y0 = EVENT_DATE_Y0;
//		rect.x1 = (STARTX_CONTENTS + WIDTH_CONTENTS) - 1;
//		rect.y1 = (EVENT_DATE_Y0 + HEIGHT_LABEL) - 1;
//		GUI_DispStringInRect(acevent_noevent_text[SettingValue[SETUP_LANGUAGE]], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
//	}
}

// PRQA S 1503 1
void MLinkEvent(void)
{
	int bCommError = gCommStatus[gDeviceIndex];
	int flagBreak = FALSE;
	nMenuPos = 0;
	nCurrIndex = 1;
	nEventIndex = gSystemEventIndex[gDeviceIndex];
	nEventTotal = gSystemEventTotalCount[gDeviceIndex];

	
(void)printf("nEventTotal = %d\n", nEventTotal);
	MLinkEventInitDisp();
	if(nEventTotal != 0)
	{
		bEventSend = TRUE;
		EventSend(TRUE);
	}

//	(void)GUI_SetFont(&GUI_Font24B_ASCII);
//	GUI_SetColor(COLOR_VALUE);
//	rect.x0 = EVENT_X0;
//	rect.y0 = EVENT_DATE_Y0;
//	rect.x1 = STARTX_CONTENTS + WIDTH_CONTENTS - 1;
//	rect.y1 = EVENT_DATE_Y0 + HEIGHT_LABEL - 1;
//	for(int i = 0 ; i < 3; i++)
//	{
////		GUI_DispStringInRect(_acevent_value_text[i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
//		rect.y0 += HEIGHT_LABEL;
//		rect.y1 += HEIGHT_LABEL;
//	}

	while (1)
	{
		E_KEY key = GetKey();

		if(key == TIME_OUT)
		{
			gStatusSendEnd = STATUS_SEND_ING;
			statusSendStep = 0;
			EventSend(FALSE);
		}
		else
		if(key == KEY_SETUP)
		{
			if(Setup() == SETUP_CHANGED)
			{
				flagBreak = TRUE;
			}
			MLinkEventInitDisp();
			gCommOldStatus[gDeviceIndex] = -1;
			(void)EventSend(TRUE);
		}
		else
		if(key == KEY_UP)
		{
			if(nEventTotal == 0)
			{
				continue;
			}
			if(nCurrIndex < nEventTotal)
			{
				nCurrIndex++;
			}
			else
			{
				nCurrIndex = 1;
			}
			bEventSend = TRUE;
			EventSend(TRUE);
			CountDisp(nEventTotal, nCurrIndex);
		}
		else
		if(key == KEY_DOWN)
		{
			if(nEventTotal == 0)
			{
				continue;
			}
			if(nCurrIndex > 1)
			{
				nCurrIndex--;
			}
			else
			{
				nCurrIndex = nEventTotal;
			}
			bEventSend = TRUE;
			EventSend(TRUE);
			CountDisp(nEventTotal, nCurrIndex);
		}
		else
		if(key == DATA_RECV)
		{
			if(bCommError == COMM_ERROR)
			{
				bCommError = COMM_OK;
				nEventTotal = gSystemEventTotalCount[gDeviceIndex];
				nCurrIndex = 1;
				gStatusSendEnd = STATUS_SEND_END;
				bEventSend = TRUE;
				if(nEventTotal != 0)
				{
					gStatusSendEnd = STATUS_SEND_END;
					(void)EventSend(TRUE);
					continue;
				}
				else
				{
					MLinkEventInitDisp();
				}
			}
			if(gStatusSendEnd == STATUS_SEND_ING)
			{
				StatusRecv();
				if(gStatusSendEnd == STATUS_SEND_ING)
				{
					(void)EventSend(FALSE);
				}
				else
				{
					(void)printf("All done!!!\n");
					g_bRecvAllDone = TRUE;
					nSendStep = 0;
					statusSendStep = 0;
					gStatusSendEnd = STATUS_SEND_ING;
				}
			}
			else
			{
				(void)printf("All done!!!\n");
				EventDataRecv();
				g_bRecvAllDone = TRUE;
				nSendStep = 0;
				statusSendStep = 0;
				gStatusSendEnd = STATUS_SEND_ING;
			}
//			
//			if(gStatusSendEnd == STATUS_SEND_ING)
//			{
//				StatusRecv();
//				EventSend();
//			}
//			else
//			if(bEventSend == TRUE)
//			{
//				EventDataRecv();
//				bEventSend = FALSE;
//				g_bRecvAllDone = TRUE;
//				nSendStep = 0;
//				statusSendStep = 0;
//				gStatusSendEnd = STATUS_SEND_ING;
//			}
//			else {}
		}
		else
		if(key == KEY_COMM_ERROR)
		{
			(void)printf("COMM Error!!! gStatusSendEnd=%d, statusSendStep=%d, nSendStep=%d\n",gStatusSendEnd,statusSendStep,nSendStep); 
			if(StatusRecvErrorProcess() == STATUS_SEND_ING)
			{
				nSendStep = 0;
			}
			else
			{
				g_bRecvAllDone = TRUE;
				(void)printf("All done!!!\n");
				gStatusSendEnd = STATUS_SEND_ING;
				statusSendStep = 0;
				nSendStep = 0;
			}
		}
		else
		if(key == COMM_STAT_ERROR)
		{
			bCommError = COMM_ERROR;
			nEventTotal = 0;
			MLinkEventInitDisp();
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else {}
		if(flagBreak == TRUE)
		{
			break;
		}
	}
}


/*************************** End of file ****************************/
