/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#define EXTERN extern
#include "stm32f4xx_hal.h"
#include "main.h"
#include "GuiData.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
//extern uint8_t KeyStatus[5];
//extern uint16_t KeyPin[5];
//extern U8 _stat[5];
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// PRQA S 1503 1
void DispMLinkStatus(void)
{
	(void)GUI_SetPenSize(STATUS_PENSIZE_LINE);
	GUI_SetColor(COLOR_MENU_NORMAL);
	GUI_SetBkColor(COLOR_MENU_NORMAL);
	GUI_ClearRect(0, 0, X1_MAIN, Y0_MAIN);
	GUI_SetColor(STATUS_LINE_COLOR);
	for(int i = 0; i < INDEX_3; i++)
	{
		GUI_DrawVLine(_ichstatus_line_x[i], 0, Y0_MAIN);
	}
	GUI_SetColor(GUI_WHITE);
	gCommOldStatus[gDeviceIndex] = -1;

}

// PRQA S 1514 2
uint8_t doStatus[DEVICE_MAX][MLINK_DO_MAX];
uint8_t diStatus[DEVICE_MAX][MLINK_DI_MAX];

// PRQA S 1503 1
void MLinkOverviewValue(int flag)
{
	static uint8_t diSetup[MLINK_DI_MAX];
	static float aiValue;

	if(gCommStatus[gDeviceIndex] == COMM_ERROR)
	{
		return;
	}
	char buf[MESSAGE_BUF_SIZE];
	(void)printf("\n\n\n\n\n MLinkOverviewValue sendStep=%d\n\n\n\n\n", nSendStep);
	if(flag)
	{
		if(nSendStep == 0)
		{
		  aiValue =  ModbusGetFloat(I_REGISTER_219);
		  (void)printf("aiValue=%f\n", aiValue);
		  return;
		}
		else
		{
			uint16_t address = H_REGISTER_2031;
			for(uint16_t i = 0; i < MLINK_DI_MAX; i++)
			{
				diSetup[i] = ModbusGetUint16(address++);
			}
			statusSendStep = 0;
			nSendStep = 0;
		}
	}
	
	(void)GUI_SetFont(&GUI_Font24B_1);
	GUI_SetColor(GUI_WHITE);
	GUI_SetBkColor(COLOR_MAIN_BG);

	GUI_RECT rect;
	rect.x0 = MLINK_OVERVIEW_VALUE1_X0;
	rect.x1 = MLINK_OVERVIEW_VALUE1_X1;
	rect.y0 = MLINK_OVERVIEW_UNIT_Y0+INDEX_5;
	rect.y1 = MLINK_OVERVIEW_UNIT_Y1-INDEX_5;
	(void)sprintf(buf, "%4.2f", aiValue);
	GUI_ClearRectEx(&rect);
	GUI_DispStringInRect(buf, &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
	
	(void)GUI_SetPenSize(PENSIZE_LINE);

	rect.x0 = MLINK_OVERVIEW_STATUS_X0;
	rect.x1 = MLINK_OVERVIEW_STATUS_X1;
	rect.y0 = MLINK_OVERVIEW_DI_BOX_Y0;
	rect.y1 = MLINK_OVERVIEW_DI_BOX_Y1;
	for(int i = 0; i < MLINK_DI_MAX; i++)
	{
		if((diSetup[i] != 0) && (diStatus[gDeviceIndex][i] == STATUS_ON))
		{
			GUI_SetBkColor(COLOR_ON);
			GUI_SetColor(COLOR_ON);
		}
		else
		{
			GUI_SetBkColor(COLOR_OFF);
			GUI_SetColor(COLOR_OFF);
		}
		GUI_FillRectEx(&rect);

		GUI_SetColor(COLOR_LINE);
		GUI_DrawRectEx(&rect);

		if(diSetup[i] == 0)		// 사용안함
		{
			(void)sprintf(buf, "-");
		}
		else
		{
			(void)sprintf(buf, "%d", i + 1);
		}
		GUI_SetColor(GUI_WHITE);
		GUI_DispStringInRect(buf, &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		rect.x0 += MLINK_OVERVIEW_STATUS_DISTANCE;
		rect.x1 += MLINK_OVERVIEW_STATUS_DISTANCE;
	}
	
	rect.y0 += MLINK_OVERVIEW_Y_DISTANCE;
	rect.y1 += MLINK_OVERVIEW_Y_DISTANCE;

	rect.x0 = MLINK_OVERVIEW_STATUS_X0;
	rect.x1 = MLINK_OVERVIEW_STATUS_X1;
	
	int do_count = MLINK_DO_MAX;
	if(mLinkMode[gDeviceIndex] == INDEX_5)
	{
		do_count = 0;
	}
	else
	if(mLinkMode[gDeviceIndex] == INDEX_3)
	{
		do_count = INDEX_2;
	}
	else {}
	
	for(int i = 0; i < MLINK_DI_MAX; i++)
	{
		if(i < do_count)
		{
			(void)sprintf(buf, "%d", i + 1);
		}
		else
		{
			(void)sprintf(buf, "-");
		}
		if((doStatus[gDeviceIndex][i] == STATUS_ON) && (i < MLINK_DO_MAX) && (i < do_count))
		{
			GUI_SetBkColor(COLOR_ON);
			GUI_SetColor(COLOR_ON);
		}
		else
		{
			GUI_SetBkColor(COLOR_OFF);
			GUI_SetColor(COLOR_OFF);
		}
		GUI_FillRectEx(&rect);

		GUI_SetColor(COLOR_LINE);
		GUI_DrawRectEx(&rect);

		GUI_SetColor(GUI_WHITE);
		GUI_DispStringInRect(buf, &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		
		rect.x0 += MLINK_OVERVIEW_STATUS_DISTANCE;
		rect.x1 += MLINK_OVERVIEW_STATUS_DISTANCE;
	}
	(void)printf("g_bRecvAllDone.......\n");
	g_bRecvAllDone = TRUE;
}


// PRQA S 1503 1
void MLinkOverview(void)
{
	GUI_SetBkColor(COLOR_MAIN_BG);
	GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);
//	DispMLinkStatus();

	GUI_SetBkColor(COLOR_MAIN_BG);
	(void)GUI_SetFont(&GUI_Font24B_1);

	(void)GUI_SetPenSize(PENSIZE_LINE);

	int y0 = MLINK_OVERVIEW_DI_BOX_Y0;
	int y1 = MLINK_OVERVIEW_DI_BOX_Y1;

	GUI_RECT rect = {
						STARTX_CONTENTS, 
						MLINK_OVERVIEW_DI_BOX_Y0,
						MLINK_OVERVIEW_VLINE_X,
						MLINK_OVERVIEW_DI_BOX_Y1
	};

	for(int i = 0; i < MLINK_TYPE_MAX; i++)
	{
		GUI_SetColor(COLOR_LINE);
		GUI_DrawRect(STARTX_CONTENTS, y0, MLINK_OVERVIEW_BOX_X1, y1);
		GUI_DrawVLine(MLINK_OVERVIEW_VLINE_X, y0, y1);
		GUI_SetColor(COLOR_LABEL);
		GUI_DispStringInRect(_acmlink_overview_label_text[i], &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		y0 += MLINK_OVERVIEW_Y_DISTANCE;
		y1 += MLINK_OVERVIEW_Y_DISTANCE;
		rect.y0 = y0;
		rect.y1 = y1;
	}

	GUI_SetColor(COLOR_UNIT);
	LanguageSelect(FONT20B);
//	(void)GUI_SetFont(&GUI_Font20B);
	rect.y0 = MLINK_OVERVIEW_UNIT_Y0;
	rect.y1 = MLINK_OVERVIEW_UNIT_Y1;
	rect.x0 = MLINK_OVERVIEW_UNIT1_X0;
	rect.x1 = MLINK_OVERVIEW_UNIT1_X1;
	GUI_DispStringInRect(_acmlink_overview_unit_text[MLINK_OVERVIEW_DI], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
}

/*************************** End of file ****************************/
