/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#define EXTERN extern
#include "stm32f4xx_hal.h"
#include "main.h"
#include "GuiData.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
static void MLinkIOSetMenu(int pos);
static void MLinkIOSetSend(int nPos);
static void MLinkIOSetAppValue(void);
static void MLinkIOSetApp(void);
static void MLinkDiMakeString(uint16_t value, char result[DATE_BUF_SIZE]);
static void MLinkIOSetDIValue(void);
static void MLinkIOSetDI(void);
static void MLinkDoMakeString(const uint16_t value, char result[DEFAULT_BUF_SIZE]);
static void MLinkIOSetDOValue(void);
static void MLinkIOSetDO(void);
static void MLinkIOSetDisp(int pos);
static void MLinkIOSetValueDisp(int pos);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

static void MLinkIOSetMenu(int pos)
{
	GUI_SetBkColor(COLOR_MAIN_BG);
	GUI_RECT rect;
	rect.x0 = ACBMCCB_MEASUR_TEXT_x0;
	rect.x1 = ACBMCCB_MEASUR_TEXT_x1;
	rect.y0 = STARTY_CONTENTS;
	rect.y1 = (STARTY_CONTENTS + ACBMCCB_MEASUR_MENU_HEIGHT) - 1;

	int y0 = STARTY_CONTENTS;
	for(int i = 0; i < (ACBMCCB_MEASUR_MENU_COUNT-1); i++)
	{
//		if(i == ACBMCCB_MEASUR_MENU_COUNT-1)
//		{
//			GUI_SetColor(COLOR_LABEL);
////			GUI_DrawRectEx(ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_Y0, ACBMCCB_RELAYSET_GRID_X1, MLINK_IOSET_APP_BOX_Y1);
//			GUI_DrawRectEx(&rect);
//			break;
//		}
		if(i == pos)
		{
			GUI_SetColor(COLOR_MENU_SELECTED);
		}
		else
		{
			GUI_SetColor(COLOR_MENU_NORMAL);
		}

		GUI_FillRect(STARTX_CONTENTS, y0, (STARTX_CONTENTS + ACBMCCB_MEASUR_MENU_WIDTH) - 1, (y0 + ACBMCCB_MEASUR_MENU_HEIGHT) - 1);

		if(i == pos)
		{
			GUI_SetColor(COLOR_VALUE);
			GUI_SetBkColor(COLOR_MENU_SELECTED);
//			(void)GUI_SetFont(&GUI_Font20B_ASCII);
			LanguageSelect(FONT20B);
		}
		else
		{
			GUI_SetColor(COLOR_LABEL);
			GUI_SetBkColor(COLOR_MENU_NORMAL);
//			(void)GUI_SetFont(&GUI_Font20_ASCII);
			LanguageSelect(FONT20);
		}

		GUI_DispStringInRect(_acmlink_iostatus_menu_text[SettingValue[SETUP_LANGUAGE]][i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += ACBMCCB_MEASUR_MENU_HEIGHT + 1;
		rect.y1 += ACBMCCB_MEASUR_MENU_HEIGHT + 1;
		y0 += ACBMCCB_MEASUR_MENU_HEIGHT + 1;;
	}
}

static void MLinkIOSetSend(int nPos)
{
	if(StatusSend() == STATUS_SEND_ING)
	{
		return;
	}
	if(nPos == INDEX_0)
	{
		ModbusSendFrame(ConnectSetting[gDeviceIndex].Address, INPUT_REGISTER, I_REGISTER_216, INDEX_1);		// 1002까지
	}
	else
	if(nPos == INDEX_1)
	{
		ModbusSendFrame(ConnectSetting[gDeviceIndex].Address, HOLDING_REGISTER, MLINK_IOSET_STEP1_READ_ADDR, MLINK_IOSET_STEP1_READ_LEN);		// 2036
	}
	else
	if(nPos == INDEX_2)
	{
		ModbusSendFrame(ConnectSetting[gDeviceIndex].Address, HOLDING_REGISTER, MLINK_IOSET_STEP2_READ_ADDR, MLINK_IOSET_STEP2_READ_LEN);		// 2027
	}
	else {}
}

static void MLinkIOSetAppValue(void)
{
	char buf[INDEX_2][DEFAULT_BUF_SIZE];

	uint16_t value = ModbusGetUint16(I_REGISTER_216) & MLINK_REMOTE_MASK;
	if((value >= INDEX_1) && (value <= INDEX_3))
	{
		(void)sprintf(buf[INDEX_0], _aclocal_remote[SettingValue[SETUP_LANGUAGE]][INDEX_1]);
	}
	else
	{
		(void)sprintf(buf[INDEX_0], _aclocal_remote[SettingValue[SETUP_LANGUAGE]][INDEX_0]);
	}
	(void)sprintf(buf[INDEX_1], "M%d", value);

	GUI_SetColor(COLOR_VALUE);
	(void)GUI_SetFont(&GUI_Font20B_ASCII);

	GUI_RECT rect;
	rect.x0 = MLINK_IOSET_VALUE_X0;
	rect.y0 = ACBMCCB_RELAYSET_GRID_Y0;
	rect.x1 = (ACBMCCB_RELAYSET_VALUE2_X0 + ACBMCCB_RELAYSET_VALUE_WIDTH) - 1;
	rect.y1 = (ACBMCCB_RELAYSET_GRID_Y0 + HEIGHT_VALUE) - 1;
	GUI_SetBkColor(COLOR_MAIN_BG);
	LanguageSelect(FONT20B);
	for(int i = 0 ; i < (LINECOUNT_CONTENTS-INDEX_4); i++)
	{
		GUI_ClearRect(rect.x0, rect.y0+1, rect.x1, rect.y1-INDEX_2);
		GUI_DispStringInRect(buf[i], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
		(void)GUI_SetFont(&GUI_Font20B_ASCII);
		rect.y0 += HEIGHT_VALUE;
		rect.y1 += HEIGHT_VALUE;
	}
	rect.x0 = MLINK_IOSET_APP_DESC_X0;
	rect.x1 = MLINK_IOSET_APP_DESC_X1;
	rect.y0 = MLINK_IOSET_APP_DESC_Y0;
	rect.y1 = rect.y0 + MLINK_IOSET_APP_DESC_Y_DISTANCE;
//	(void)GUI_SetFont(&GUI_Font16B_ASCII);
	LanguageSelect(FONT16B);
	if((value >= 1) && (value <= INDEX_5))
	{
		for(int i = 0 ; i < INDEX_4; i++)
		{
			GUI_ClearRect(rect.x0, rect.y0+1, rect.x1, rect.y1-INDEX_2);
			GUI_DispStringInRect(_acappdesc_label_text[SettingValue[SETUP_LANGUAGE]][value-1][i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
			GUI_SetColor(COLOR_LABEL);
//			(void)GUI_SetFont(&GUI_Font16_ASCII);
			rect.y0 += MLINK_IOSET_APP_DESC_Y_DISTANCE;
			rect.y1 += MLINK_IOSET_APP_DESC_Y_DISTANCE;
			rect.x0 = MLINK_IOSET_APP_DESC2_X0;
			rect.x1 = MLINK_IOSET_APP_DESC2_X1;
		}
	}
}

static void MLinkIOSetApp(void)
{
	GUI_DrawRect(ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_Y0, ACBMCCB_RELAYSET_GRID_X1, MLINK_IOSET_APP_BOX_Y1);

//	for(int i = 0; i < LINECOUNT_CONTENTS-5; i++)
	{
//		int y0 = ACBMCCB_RELAYSET_GRID_Y0 + (i + 1) * HEIGHT_VALUE;
		int y0 = ACBMCCB_RELAYSET_GRID_Y0 + ((0 + 1) * HEIGHT_VALUE);
		GUI_DrawHLine(y0, ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_X1);
	}

	GUI_SetColor(COLOR_LABEL);
//	(void)GUI_SetFont(&GUI_Font20_ASCII);
	LanguageSelect(FONT20);

	GUI_RECT rect;
	rect.x0 = ACBMCCB_RELAYSET_LABEL2_X0;
	rect.x1 = ACBMCCB_RELAYSET_LABEL3_X0; // +  ACBMCCB_RELAYSET_LABEL2_WIDTH - 1;
	rect.y0 = ACBMCCB_RELAYSET_GRID_Y0;
	rect.y1 = (ACBMCCB_RELAYSET_GRID_Y0 +  HEIGHT_LABEL) - 1;

	for(int j= 0 ; j < (LINECOUNT_CONTENTS-INDEX_4); j++)
	{
		GUI_DispStringInRect(_acmlink_iostatusAPP_value_text[SettingValue[SETUP_LANGUAGE]][0][j], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += HEIGHT_LABEL;
		rect.y1 += HEIGHT_LABEL;
	}

}

static void MLinkDiMakeString(uint16_t value, char result[DATE_BUF_SIZE])
{
	if(value == NotUsed)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_0]);
	}
	else
	if(value == ContactAx)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_1]);		// ???확인
	}
	else
	if(value == ContactAl)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_2]);		// ???확인
	}
	else
	if(value == Contact)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_3]);
	}
	else
	if(value == ContactAx2)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_4]);		// ???확인
	}
	else
	if(value == ContactAl2)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_5]);		// ???확인
	}
	else
	if(value == PulseWh)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_6]);
	}
	else
	if(value == PulseVarh)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_7]);
	}
	else
	if(value == PulseVAh)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_8]);
	}
	else
	if(value == Pulse)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_9]);
	}
	else
	if(value == ContactLI)
	{
		(void)sprintf(result, _acmlinkiostatusDI_value_text[SettingValue[SETUP_LANGUAGE]][INDEX_10]);
	}
	else
	{
		(void)sprintf(result, "(%02x)", value);
	}
}

static void MLinkIOSetDIValue(void)
{
	char buf[DATE_BUF_SIZE];

	GUI_SetColor(COLOR_VALUE);
//	(void)GUI_SetFont(&GUI_Font20B_ASCII);
	LanguageSelect(FONT20B);


	GUI_RECT rect;
	rect.x0 = ACBMCCB_RELAYSET_VALUE1_X0;
	rect.y0 = ACBMCCB_RELAYSET_GRID_Y0;
	rect.x1 = (ACBMCCB_RELAYSET_VALUE2_X0 + ACBMCCB_RELAYSET_VALUE_WIDTH) - 1;
	rect.y1 = (ACBMCCB_RELAYSET_GRID_Y0 + HEIGHT_VALUE) - 1;
	uint16_t index = H_REGISTER_2031;
	GUI_SetBkColor(COLOR_MAIN_BG);
	for(int i = 0 ; i < LINECOUNT_CONTENTS; i++, index++)
	{
		MLinkDiMakeString(ModbusGetUint16(index), buf);
		GUI_ClearRect(rect.x0, rect.y0+1, rect.x1, rect.y1-INDEX_2);
		GUI_DispStringInRect(buf, &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
		rect.y0 += HEIGHT_VALUE;
		rect.y1 += HEIGHT_VALUE;
	}
}

static void MLinkIOSetDI(void)
{

	GUI_DrawRect(ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_Y0, ACBMCCB_RELAYSET_GRID_X1, ACBMCCB_RELAYSET_GRID_Y0 + (INDEX_6 * HEIGHT_VALUE));

	for(int i = 0; i < (LINECOUNT_CONTENTS-1); i++)
	{
		int y0 = ACBMCCB_RELAYSET_GRID_Y0 + ((i + 1) * HEIGHT_VALUE);
		GUI_DrawHLine(y0, ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_X1);
	}
//	GUI_DrawVLine(ACBMCCB_RELAYSET_GRID_X, ACBMCCB_RELAYSET_GRID_Y0, ACBMCCB_RELAYSET_GRID_Y0 + (3 * HEIGHT_VALUE));

	GUI_SetColor(COLOR_LABEL);
	(void)GUI_SetFont(&GUI_Font20_ASCII);

	GUI_RECT rect;
	rect.x0 = ACBMCCB_RELAYSET_LABEL2_X0;
	rect.x1 = ACBMCCB_RELAYSET_LABEL3_X0; // +  ACBMCCB_RELAYSET_LABEL2_WIDTH - 1;
//	rect.x1 = ACBMCCB_RELAYSET_LABEL2_X0 +  ACBMCCB_RELAYSET_LABEL2_WIDTH - 1;
	rect.y0 = ACBMCCB_RELAYSET_GRID_Y0;
	rect.y1 = (ACBMCCB_RELAYSET_GRID_Y0 +  HEIGHT_LABEL) - 1;


	for(int j= 0 ; j < LINECOUNT_CONTENTS; j++)
	{
		GUI_DispStringInRect(_acmlinkiostatusDI_label_text[j], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += HEIGHT_LABEL;
		rect.y1 += HEIGHT_LABEL;
	}
}

static void MLinkDoMakeString(const uint16_t value, char result[DEFAULT_BUF_SIZE])
{
	if(value == INDEX_2)
	{
		(void)sprintf(result, _acmlink_iostatusDO_value[SettingValue[SETUP_LANGUAGE]][INDEX_2]);
	}
	else
	if(value == INDEX_1)
	{
		(void)sprintf(result, _acmlink_iostatusDO_value[SettingValue[SETUP_LANGUAGE]][INDEX_1]);
	}
	else
	{
		(void)sprintf(result, _acmlink_iostatusDO_value[SettingValue[SETUP_LANGUAGE]][INDEX_0]);
	}
}

static void MLinkIOSetDOValue(void)
{
	char buf[DEFAULT_BUF_SIZE];

	GUI_SetColor(COLOR_VALUE);
	(void)GUI_SetFont(&GUI_Font20B_ASCII);

	GUI_RECT rect;
	rect.x0 = ((ACBMCCB_RELAYSET_VALUE2_X0 - ACBMCCB_RELAYSET_VALUE_WIDTH) + INDEX_50);
	rect.y0 = ACBMCCB_RELAYSET_GRID_Y0;
	rect.x1 = (((ACBMCCB_RELAYSET_VALUE2_X0 + ACBMCCB_RELAYSET_VALUE_WIDTH) - 1) - INDEX_50);
	rect.y1 = (ACBMCCB_RELAYSET_GRID_Y0 + HEIGHT_VALUE) - 1;
	uint16_t val = ModbusGetUint16(H_REGISTER_2021);
	if(val == INDEX_2)
	{
		(void)sprintf(buf, "Not SBO");
	}
	else
	{
		(void)sprintf(buf, "SBO");
	}
	GUI_SetBkColor(COLOR_MAIN_BG);
	GUI_ClearRect(rect.x0, rect.y0+1, rect.x1, rect.y1-INDEX_2);
	GUI_DispStringInRect(buf, &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
	rect.y0 += HEIGHT_VALUE;
	rect.y1 += HEIGHT_VALUE;
	LanguageSelect(FONT20B);

	uint16_t doSetting[INDEX_4];
	for(int i = 0 ; i < INDEX_4; i++)
	{
		doSetting[i] = ModbusGetUint16(H_REGISTER_2024+i);
		if((mLinkMode[gDeviceIndex] == INDEX_3) && (i >= INDEX_2))
		{
			doSetting[i] = INDEX_2;
		}
		if(mLinkMode[gDeviceIndex] == INDEX_5)
		{
			doSetting[i] = INDEX_2;
		}
	}

	for(int i = 0 ; i < (LINECOUNT_CONTENTS-INDEX_2); i++)
	{
		MLinkDoMakeString(doSetting[i], buf);
		GUI_ClearRect(rect.x0, rect.y0+1, rect.x1, rect.y1-INDEX_2);
		GUI_DispStringInRect(buf, &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
		rect.y0 += HEIGHT_VALUE;
		rect.y1 += HEIGHT_VALUE;
	}
}

static void MLinkIOSetDO(void)
{
	GUI_DrawRect(ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_Y0, ACBMCCB_RELAYSET_GRID_X1, ACBMCCB_RELAYSET_GRID_Y0 + (INDEX_5 * HEIGHT_VALUE));

	for(int i = 0; i < (LINECOUNT_CONTENTS-INDEX_2); i++)
	{
		int y0 = ACBMCCB_RELAYSET_GRID_Y0 + ((i + 1) * HEIGHT_VALUE);
		GUI_DrawHLine(y0, ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_X1);
	}

	GUI_SetColor(COLOR_LABEL);
	(void)GUI_SetFont(&GUI_Font20_ASCII);

	GUI_RECT rect;
	rect.x0 = ACBMCCB_RELAYSET_LABEL2_X0;
	rect.x1 = ACBMCCB_RELAYSET_LABEL3_X0; // +  ACBMCCB_RELAYSET_LABEL2_WIDTH - 1;
	rect.y0 = ACBMCCB_RELAYSET_GRID_Y0;
	rect.y1 = (ACBMCCB_RELAYSET_GRID_Y0 +  HEIGHT_LABEL) - 1;

	for(int j= 0 ; j < (LINECOUNT_CONTENTS-1); j++)
	{
		GUI_DispStringInRect(_acmlink_iostatusDO_value_text[j], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += HEIGHT_LABEL;
		rect.y1 += HEIGHT_LABEL;
	}
}

static void MLinkIOSetDisp(int pos)
{
	GUI_SetBkColor(COLOR_MAIN_BG);
	GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);
	(void)GUI_SetPenSize(PENSIZE_LINE);

	MLinkIOSetMenu(pos);

	GUI_SetBkColor(COLOR_MAIN_BG);
	GUI_SetColor(COLOR_LINE);

	GUI_ClearRect(ACBMCCB_RELAYSET_GRID_X0, ACBMCCB_RELAYSET_GRID_Y0, ACBMCCB_RELAYSET_GRID_X1, Y1_MAIN);

	if(pos == INDEX_0)
	{
		MLinkIOSetApp();
	}
	else
	if(pos == INDEX_1)
	{
		MLinkIOSetDI();
	}
	else
	if(pos == INDEX_2)
	{
		MLinkIOSetDO();
	}
	else {}
}

static void MLinkIOSetValueDisp(int pos)
{
	if(pos == INDEX_0)
	{
		MLinkIOSetAppValue();
	}
	else
	if(pos == INDEX_1)
	{
		MLinkIOSetDIValue();
	}
	else
	if(pos == INDEX_2)
	{
		MLinkIOSetDOValue();
	}
	else {}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       MLinkIOSet
*/

// PRQA S 1503 1
void MLinkIOSet(void)
{
	int flagBreak = FALSE;
	nMenuPos = 0;

	(void)GUI_SetFont(&GUI_Font20_ASCII);
	GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);

	MLinkIOSetDisp(nMenuPos);
	ReadyToSend();
	MLinkIOSetSend(nMenuPos);

	while (1)
    {
		E_KEY key = GetKey();

		if(key == TIME_OUT)
		{
			gStatusSendEnd = STATUS_SEND_ING;
			nSendStep = 0;
			statusSendStep = 0;
			MLinkIOSetSend(nMenuPos);
		}
		else
		if(key == KEY_SETUP)
		{
			if(Setup() == SETUP_CHANGED)
			{
				flagBreak = TRUE;
			}
			GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);
			MLinkIOSetDisp(nMenuPos);
			gCommOldStatus[gDeviceIndex] = -1;
		}
		else
		if(key == KEY_UP)
		{
			if(nMenuPos > 0)
			{
				nMenuPos--;
			}
			else
			{
				nMenuPos = ACBMCCB_MEASUR_MENU_COUNT - INDEX_2;
			}
			MLinkIOSetDisp(nMenuPos);
			ReadyToSend();
			MLinkIOSetSend(nMenuPos);
		}
		else
		if(key == KEY_DOWN)
		{
			if(nMenuPos < (ACBMCCB_MEASUR_MENU_COUNT-INDEX_2))
			{
				nMenuPos++;
			}
			else
			{
				nMenuPos = 0;
			}
			MLinkIOSetDisp(nMenuPos);
			ReadyToSend();
			MLinkIOSetSend(nMenuPos);
		}
		else
		if(key == DATA_RECV)
		{
			if(gStatusSendEnd == STATUS_SEND_ING)
			{
				StatusRecv();
				MLinkIOSetSend(nMenuPos);
			}
			else
			{
				MLinkIOSetValueDisp(nMenuPos);
				g_bRecvAllDone = TRUE;
				(void)printf("All done!!!\n");
			}
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else
		if(key == KEY_COMM_ERROR)
		{
			(void)printf("COMM Error!! gStatusSendEnd=%d, statusSendStep=%d\n",gStatusSendEnd,statusSendStep);
			if(StatusRecvErrorProcess() == STATUS_SEND_ING)
			{
				nSendStep = 0;
			}
			else
			{
				MLinkIOSetSend(nMenuPos);
				g_bRecvAllDone = TRUE;

				(void)printf("All done!!!\n");
				gStatusSendEnd = STATUS_SEND_ING;
				statusSendStep = 0;
				nSendStep = 0;
			}
		}
		else
		if(key == COMM_STAT_ERROR)
		{
			GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);
			MLinkIOSetDisp(nMenuPos);
		}
		else {}
		if(flagBreak == TRUE)
		{
			break;
		}
	}
}

/*************************** End of file ****************************/
