/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#define EXTERN extern
#include "stm32f4xx_hal.h"
#include "main.h"
#include "GuiData.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

// USER START (Optionally insert additional defines)
static void PasswordButtonDisp(int button);
static void PasswordChangeDisp(int pos, const char oldPassword[CONTROL_PASSWORD_DIGIT+1], const char newPassword[CONTROL_PASSWORD_DIGIT+1]);
// USER END

static void PasswordButtonDisp(int button)
{
	GUI_RECT rect;
	rect.x0 = CONTROL_BUTTON_X;
	rect.y0 = CONTROL_BUTTON_Y;
	rect.x1 = (CONTROL_BUTTON_X + CONTROL_BUTTON_WIDTH) - 1;
	rect.y1 = (CONTROL_BUTTON_Y + CONTROL_BUTTON_HEIGHT) - 1;
	LanguageSelect(FONT24);
	for(int i = 0; i < CONTROL_BUTTON_NOSELECT; i++)
	{
		if(i == button)
		{
			GUI_SetColor(COLOR_MENU_SELECTED);
			GUI_SetBkColor(COLOR_MENU_SELECTED);
		}
		else
		{
			GUI_SetColor(CONTROL_NORMAL_BUTTON);
			GUI_SetBkColor(CONTROL_NORMAL_BUTTON);
		}
//		(void)GUI_SetFont(&GUI_Font24B_ASCII);
		GUI_FillRoundedRect(rect.x0, rect.y0, rect.x1, rect.y1, INDEX_2);
		if(i == button)
		{
			GUI_SetColor(SELECTED_TEXT_COLOR);
		}
		else
		{
			GUI_SetColor(CONTROL_NORMAL_COLOR);
		}

		GUI_DispStringInRect(_apassword_button_text[SettingValue[SETUP_LANGUAGE]][i], &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		rect.x0 += CONTROL_BUTTON_WIDTH + CONTROL_BTTON_DISTANCE;
		rect.x1 += CONTROL_BUTTON_WIDTH + CONTROL_BTTON_DISTANCE;
	}
}

// PRQA S 1505 1
int QuestionMessage(void)
{
	int flagBreak = FALSE;
	int nPos = 0;
	int ret = FALSE;
	GUI_RECT rect;

	GUI_SetBkColor(COLOR_MENU_NORMAL);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_MENU_SELECTED);

	GUI_ClearRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);
	GUI_DrawRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);

	GUI_SetColor(SELECTED_TEXT_COLOR);
//	(void)GUI_SetFont(&GUI_Font24_ASCII);
	LanguageSelect(FONT24);
	rect.x0 = PASSWORD_MSG_X0;
	rect.y0 = PASSWORD_MSG_Y0;
	rect.x1 = PASSWORD_MSG_X1;
	rect.y1 = PASSWORD_MSG_Y1;
	GUI_DispStringInRect(_acpassword_question_text[SettingValue[SETUP_LANGUAGE]], &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

	PasswordButtonDisp(CONTROL_BUTTON_OK);

	while (1)
	{
		E_KEY key = GetKey();

		if(key == KEY_UP)
		{
			if(nPos == 1)
			{
				PasswordButtonDisp(CONTROL_BUTTON_OK);
				nPos = 0;
			}
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPos == 0)
			{
				PasswordButtonDisp(CONTROL_BUTTON_CANCEL);
				nPos = 1;
			}
		}
		else
		if(key == KEY_ENTER)
		{
			if(nPos == 0)	// Retry 이면
			{
				ret = TRUE;
				flagBreak = TRUE;
			}
			else
			if(nPos == 1)	// Cancel 이면
			{
				flagBreak = TRUE;
			}
			else {}
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else {}
		if(flagBreak == TRUE)
		{
			break;
		}
	}
	return ret;
}

static void PasswordChangeDisp(int pos, const char oldPassword[CONTROL_PASSWORD_DIGIT+1], const char newPassword[CONTROL_PASSWORD_DIGIT+1])
{
	GUI_RECT rect;
	GUI_SetBkColor(COLOR_MENU_NORMAL);
//	GUI_ClearRect(X0_MAIN, Y0_MAIN, X1_MAIN, Y1_MAIN);

	GUI_SetBkColor(COLOR_MENU_NORMAL);
	GUI_ClearRect(PASSWORD_CHANGE_LABEL_X0,
				  PASSWORD_OLD_INTPUT_Y0 - INDEX_17,
				  PASSWORD_CHANGE_VALUE_X + (PASSWORD_CHANGE_WIDTH * INDEX_4),
				  PASSWORD_NEW_INTPUT_Y1 + INDEX_17);

	GUI_SetColor(COLOR_LABEL);
//	(void)GUI_SetFont(&GUI_Font20_ASCII);
	LanguageSelect(FONT20B);
	rect.x0 = PASSWORD_CHANGE_LABEL_X0-INDEX_20;
	rect.y0 = PASSWORD_OLD_INTPUT_Y0;
	rect.x1 = PASSWORD_CHANGE_LABEL_X1;
	rect.y1 = PASSWORD_OLD_INTPUT_Y1;
	GUI_DispStringInRect(_acsetup_password_text[SettingValue[SETUP_LANGUAGE]][0], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
	rect.y0 = PASSWORD_NEW_INTPUT_Y0;
	rect.y1 = PASSWORD_NEW_INTPUT_Y1;
	GUI_DispStringInRect(_acsetup_password_text[SettingValue[SETUP_LANGUAGE]][1], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);


	rect.x0 = PASSWORD_CHANGE_VALUE_X;
	rect.y0 = PASSWORD_OLD_INTPUT_Y0;
	rect.x1 = (PASSWORD_CHANGE_VALUE_X + PASSWORD_CHANGE_WIDTH) - 1;
	rect.y1 = PASSWORD_OLD_INTPUT_Y1;
	for(int i = 0; i < PASSWORD_CHANGE_DIGIT; i++)
	{
		GUI_DispStringInRect(_acpassword_input_text, &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		rect.x0 += PASSWORD_CHANGE_WIDTH;
		rect.x1 += PASSWORD_CHANGE_WIDTH;
		if(i == INDEX_3)
		{
			rect.x0 = PASSWORD_CHANGE_VALUE_X;
			rect.x1 = (PASSWORD_CHANGE_VALUE_X + PASSWORD_CHANGE_WIDTH) - 1;
			rect.y0 = PASSWORD_NEW_INTPUT_Y0;
			rect.y1 = PASSWORD_NEW_INTPUT_Y1;
		}
	}

	if(pos >= PASSWORD_CHANGE_DIGIT)
	{
		return;
	}

	char buf[INDEX_2];
	int offset;
	if(pos < INDEX_4)
	{
		offset = pos;
		buf[0] = oldPassword[pos];
		rect.y0 = PASSWORD_OLD_INTPUT_Y0;
		rect.y1 = PASSWORD_OLD_INTPUT_Y1;
	}
	else
	{
		offset = pos - INDEX_4;
		buf[0] = newPassword[pos-INDEX_4];
		rect.y0 = PASSWORD_NEW_INTPUT_Y0;
		rect.y1 = PASSWORD_NEW_INTPUT_Y1;
	}
	buf[1] = 0;

	rect.x0 = PASSWORD_CHANGE_VALUE_X + (PASSWORD_CHANGE_WIDTH * offset);
	rect.x1 = (rect.x0 + PASSWORD_CHANGE_WIDTH) - 1;

	GUI_SetColor(SELECTED_TEXT_COLOR);
	GUI_SetBkColor(GUI_BLACK);
	GUI_ClearRect(rect.x0, rect.y0, rect.x1, rect.y1);
	GUI_DispStringInRect(buf, &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

	int x = rect.x0 - INDEX_7;
	(void)GUI_BMP_Draw(_acUp, x, rect.y0 - INDEX_17);
	(void)GUI_BMP_Draw(_acDown, x, rect.y1);
}

// PRQA S 1503 1
int PasswordChange(void)
{
	int flagBreak = FALSE;
	int nPos = 0;
	int ret = FALSE;
	char oldPassword[CONTROL_PASSWORD_DIGIT+1];
	char newPassword[CONTROL_PASSWORD_DIGIT+1];

	(void)sprintf(oldPassword, "0000");
	(void)sprintf(newPassword, "0000");

	GUI_SetBkColor(COLOR_MENU_NORMAL);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_MENU_SELECTED);

	GUI_ClearRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);
	GUI_DrawRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);

	GUI_SetColor(SELECTED_TEXT_COLOR);

	PasswordChangeDisp(nPos, oldPassword, newPassword);
	ButtonDisp(CONTROL_BUTTON_NOSELECT);

	while (1)
	{
		E_KEY key = GetKey();
		int index;

		if(key == KEY_UP)
		{
			if(nPos < PASSWORD_CHANGE_DIGIT)
			{
				if(nPos < INDEX_4)
				{
					index =  nPos;
					if(oldPassword[index] < '9')
					{
						oldPassword[index]++;
					}
					else
					{
						oldPassword[index] = '0';
					}
					PasswordChangeDisp(nPos, oldPassword, newPassword);
				}
				else
				{
					index =  nPos - INDEX_4;
					if(newPassword[index] < '9')
					{
						newPassword[index]++;
					}
					else
					{
						newPassword[index] = '0';
					}
					PasswordChangeDisp(nPos, oldPassword, newPassword);
				}
			}
			else
			if(nPos == (PASSWORD_CHANGE_DIGIT + 1))
			{
				ButtonDisp(CONTROL_BUTTON_OK);
				nPos = PASSWORD_CHANGE_DIGIT;
			}
			else {}
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPos < PASSWORD_CHANGE_DIGIT)
			{
				if(nPos < INDEX_4)
				{
					index = nPos;
					if(oldPassword[index] > '0')
					{
						oldPassword[index]--;
					}
					else
					{
						oldPassword[index] = '9';
					}
					PasswordChangeDisp(nPos, oldPassword, newPassword);
				}
				else
				{
					index = nPos - INDEX_4;
					if(newPassword[index] > '0')
					{
						newPassword[index]--;
					}
					else
					{
						newPassword[index] = '9';
					}
					PasswordChangeDisp(nPos, oldPassword, newPassword);
				}
			}
			else
			if(nPos == PASSWORD_CHANGE_DIGIT)
			{
				ButtonDisp(CONTROL_BUTTON_CANCEL);
				nPos = PASSWORD_CHANGE_DIGIT + 1;
			}
			else {}
		}
		else
		if(key == KEY_ENTER)
		{
			if(nPos < PASSWORD_CHANGE_DIGIT)
			{
				nPos++;
				PasswordChangeDisp(nPos, oldPassword, newPassword);
				if(nPos == PASSWORD_CHANGE_DIGIT)
				{
					ButtonDisp(CONTROL_BUTTON_OK);
				}
			}
			else
			if(nPos == PASSWORD_CHANGE_DIGIT)	// OK 이면
			{
				uint16_t  password = atoi(oldPassword);
				if(password != SettingValue[SETUP_PASSWORD])
				{
					if(QuestionMessage() == FALSE)
					{
						flagBreak = TRUE;
					}
					nPos = 0;
					PasswordChangeDisp(nPos, oldPassword, newPassword);
					ButtonDisp(CONTROL_BUTTON_NOSELECT);
				}
				else
				{
					SettingValue[SETUP_PASSWORD] = atoi(newPassword);
					ret = TRUE;
					flagBreak = TRUE;
				}
			}
			else
			if(nPos == (PASSWORD_CHANGE_DIGIT + 1))	// Cancel 이면
			{
				flagBreak = TRUE;
			}
			else {}
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else {}
		if(flagBreak == TRUE)
		{
			break;
		}
	}
	return ret;
}

/*************************** End of file ****************************/
