/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#define EXTERN extern
#include "stm32f4xx_hal.h"
#include "main.h"
#include "GuiData.h"

static void DateTimeDisp(int pos);
static int LeapYear(uint16_t year);
static uint16_t GetDaysInMonth(uint16_t year, uint16_t month);

S_DATE_TIME changeDateTime;

static int LeapYear(uint16_t year)	// 올해가 윤년인가 ?
{
    if((((year % INDEX_4) == 0) && ((year % HUNDRED) != 0)) || ((year % INDEX_400) == 0))
	{
        return(TRUE);
	}
    else
	{
        return(FALSE);
	}
}

static uint16_t GetDaysInMonth(uint16_t year, uint16_t month)
{
	static uint16_t g_DaysInMonth[] = {
		INDEX_31, INDEX_28, INDEX_31, INDEX_30, INDEX_31, INDEX_30, INDEX_31, INDEX_31, INDEX_30, INDEX_31, INDEX_30, INDEX_31
	};

	uint16_t nDays;

	nDays = g_DaysInMonth[month-1];
	if((LeapYear(year) == TRUE) && (month == INDEX_2))
	{
		nDays++;
	}
	return nDays;
}

static void DateTimeDisp(int pos)
{

	GUI_RECT rect;
	GUI_SetBkColor(COLOR_MENU_NORMAL);
	GUI_ClearRect(POPUP_WINDOW_X0+1, SETUP_INPUT_Y0 - INDEX_17, POPUP_WINDOW_X1-1, SETUP_INPUT_Y1 + INDEX_17);

	(void)GUI_SetFont(&GUI_Font32B_ASCII);
	GUI_SetColor(SELECTED_TEXT_COLOR);

	rect.x0 = POPUP_WINDOW_X0;
	rect.y0 = SETUP_INPUT_Y0;
	rect.x1 = POPUP_WINDOW_X1;
	rect.y1 = SETUP_INPUT_Y1;

	char buf[MESSAGE_BUF_SIZE];
	(void)sprintf(buf, "%04d - %02d - %02d  %02d : %02d : %02d", changeDateTime.Year, changeDateTime.Month, changeDateTime.Day, changeDateTime.Hour, changeDateTime.Min, changeDateTime.Sec);
	GUI_DispStringInRect(buf, &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

	if(pos >= SETUP_TIMESET_COUNT)
	{
		return;
	}

	rect.x0 = date_set_pos[pos][0];
	rect.y0 = SETUP_INPUT_Y0;
	rect.x1 = date_set_pos[pos][1];
	rect.y1 = SETUP_INPUT_Y1;
	GUI_SetBkColor(GUI_BLACK);
	GUI_ClearRect(rect.x0, rect.y0, rect.x1, rect.y1);
	if(pos == INDEX_0)
	{
	   (void)sprintf(buf, "%04d", changeDateTime.Year);
	}
	else
	if(pos == INDEX_1)
	{
	   (void)sprintf(buf, "%02d", changeDateTime.Month);
	}
	else
	if(pos == INDEX_2)
	{
	   (void)sprintf(buf, "%02d", changeDateTime.Day);
	}
	else
	if(pos == INDEX_3)
	{
	   (void)sprintf(buf, "%02d", changeDateTime.Hour);
	}
	else
	if(pos == INDEX_4)
	{
	   (void)sprintf(buf, "%02d", changeDateTime.Min);
	}
	else
	if(pos == INDEX_5)
	{
	   (void)sprintf(buf, "%02d", changeDateTime.Sec);
	}
	else {}

	GUI_DispStringInRect(buf, &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

	(void)GUI_BMP_Draw(_acUp, date_set_updown_pos[pos], SETUP_INPUT_Y0 - INDEX_17);
	(void)GUI_BMP_Draw(_acDown, date_set_updown_pos[pos], SETUP_INPUT_Y1);
}

// PRQA S 1505 1
void ButtonDisp(int button)
{
	GUI_RECT rect;
	rect.x0 = CONTROL_BUTTON_X;
	rect.y0 = CONTROL_BUTTON_Y;
	rect.x1 = (CONTROL_BUTTON_X + CONTROL_BUTTON_WIDTH) - 1;
	rect.y1 = (CONTROL_BUTTON_Y + CONTROL_BUTTON_HEIGHT) - 1;
	LanguageSelect(FONT24B);
	for(int i = 0; i < CONTROL_BUTTON_NOSELECT; i++)
	{
		if(i == button)
		{
			GUI_SetColor(COLOR_MENU_SELECTED);
			GUI_SetBkColor(COLOR_MENU_SELECTED);
		}
		else
		{
			GUI_SetColor(CONTROL_NORMAL_BUTTON);
			GUI_SetBkColor(CONTROL_NORMAL_BUTTON);
		}
		GUI_FillRoundedRect(rect.x0, rect.y0, rect.x1, rect.y1, INDEX_2);
		if(i == button)
		{
			GUI_SetColor(SELECTED_TEXT_COLOR);
		}
		else
		{
			GUI_SetColor(CONTROL_NORMAL_COLOR);
		}
		GUI_DispStringInRect(_accontrol_button_text[SettingValue[SETUP_LANGUAGE]][i], &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
		rect.x0 += CONTROL_BUTTON_WIDTH + CONTROL_BTTON_DISTANCE;
		rect.x1 += CONTROL_BUTTON_WIDTH + CONTROL_BTTON_DISTANCE;
	}
}

// PRQA S 1503 1
void SettingTime(void)
{
	int flagBreak = FALSE;
	int nPos = 0;

	GUI_SetBkColor(COLOR_MENU_NORMAL);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_MENU_SELECTED);

	GUI_ClearRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);
	GUI_DrawRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);

	GUI_SetColor(SELECTED_TEXT_COLOR);
	(void)GUI_SetFont(&GUI_Font32B_ASCII);

	changeDateTime.Year = gDateTime.Year;
	changeDateTime.Month = gDateTime.Month;
	changeDateTime.Day = gDateTime.Day;
	changeDateTime.Hour = gDateTime.Hour;
	changeDateTime.Min = gDateTime.Min;
	changeDateTime.Sec = gDateTime.Sec;
	DateTimeDisp(nPos);
	ButtonDisp(CONTROL_BUTTON_NOSELECT);

	uint16_t year = (uint16_t)changeDateTime.Year;
	uint16_t days;
	while (1)
	{
		E_KEY key = GetKey();

		if(key == KEY_UP)
		{
			if(nPos < SETUP_TIMESET_COUNT)
			{
				if(nPos == INDEX_0)
				{
					if(year < YEAR_MAX)
					{
						year++;
					}
				}
				else
				if(nPos == INDEX_1)
				{
					if(changeDateTime.Month < MONTH_MAX)
					{
						changeDateTime.Month++;
					}
					else
					{
						changeDateTime.Month = 1;
					}
					days = GetDaysInMonth(year, changeDateTime.Month);
					if(changeDateTime.Day > days)
					{
						changeDateTime.Day = days;
					}
				}
				else
				if(nPos == INDEX_2)
				{
					days = DAY_MAX;
					days = GetDaysInMonth(year, changeDateTime.Month);
					if(changeDateTime.Day < days)
					{
						changeDateTime.Day++;
					}
					else
					{
						changeDateTime.Day = 1;
					}
				}
				else
				if(nPos == INDEX_3)
				{
					if(changeDateTime.Hour < (HOUR_MAX - 1))
					{
						changeDateTime.Hour++;
					}
					else
					{
						changeDateTime.Hour = 0;
					}
				}
				else
				if(nPos == INDEX_4)
				{
					if(changeDateTime.Min < (MIN_MAX - 1))
					{
						changeDateTime.Min++;
					}
					else
					{
						changeDateTime.Min = 0;
					}
				}
				else
				if(nPos == INDEX_5)
				{
					if(changeDateTime.Sec < (MIN_MAX - 1))
					{
						changeDateTime.Sec++;
					}
					else
					{
						changeDateTime.Sec = 0;
					}
				}
				else {}
				changeDateTime.Year = year;
				DateTimeDisp(nPos);
			}
			else
			if(nPos == (SETUP_TIMESET_COUNT + 1))
			{
				ButtonDisp(CONTROL_BUTTON_OK);
				nPos = SETUP_TIMESET_COUNT;
			}
			else {}
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPos < SETUP_TIMESET_COUNT)
			{
				if(nPos == INDEX_0)
				{
					if(year > YEAR_MIN)
					{
						year--;
					}
				}
				else
				if(nPos == INDEX_1)
				{
					if(changeDateTime.Month > 1)
					{
						changeDateTime.Month--;
					}
					else
					{
						changeDateTime.Month = MONTH_MAX;
					}
					days = GetDaysInMonth(year, changeDateTime.Month);
					if(changeDateTime.Day > days)
					{
						changeDateTime.Day = days;
					}
				}
				else
				if(nPos == INDEX_2)
				{
					days = DAY_MAX;
					days = GetDaysInMonth(year, changeDateTime.Month);
					if(changeDateTime.Day > 1)
					{
						changeDateTime.Day--;
					}
					else
					{
						changeDateTime.Day = days;
					}
				}
				else
				if(nPos == INDEX_3)
				{
					if(changeDateTime.Hour > 0)
					{
						changeDateTime.Hour--;
					}
					else
					{
						changeDateTime.Hour = HOUR_MAX - 1;
					}
				}
				else
				if(nPos == INDEX_4)
				{
					if(changeDateTime.Min > 0)
					{
						changeDateTime.Min--;
					}
					else
					{
						changeDateTime.Min = MIN_MAX - 1;
					}
				}
				else
				if(nPos == INDEX_5)
				{
					if(changeDateTime.Sec > 0)
					{
						changeDateTime.Sec--;
					}
					else
					{
						changeDateTime.Sec = MIN_MAX - 1;
					}
				}
				else {}
				changeDateTime.Year = year;
				DateTimeDisp(nPos);
			}
			else
			if(nPos == SETUP_TIMESET_COUNT)
			{
				ButtonDisp(CONTROL_BUTTON_CANCEL);
				nPos = SETUP_TIMESET_COUNT + 1;
			}
			else {}
		}
		else
		if(key == KEY_ENTER)
		{
			if(nPos < SETUP_TIMESET_COUNT)
			{
				nPos++;
				changeDateTime.Year = year;
				DateTimeDisp(nPos);
				if(nPos == SETUP_TIMESET_COUNT)
				{
					ButtonDisp(CONTROL_BUTTON_OK);
				}
			}
			else
			if(nPos == SETUP_TIMESET_COUNT)	// OK 이면
			{
				(void)printf("===============\nOK\n");
				(void)PCF2127_set_time();
				gbSetTime = true;
/*
				for(int i = 0; i < gDeviceCount; i++)
				{
					ModbusSetTimeAndWait(ConnectSetting[i].Address, &gDateTime);
				}
*/
				flagBreak = TRUE;
			}
			else
			if(nPos == (SETUP_TIMESET_COUNT + 1))	// Cancel 이면
			{
				(void)printf("===============\nCancel\n");
				flagBreak = TRUE;
			}
			else {}
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else {}
		if(flagBreak == TRUE)
		{
			break;
		}
	}
}

/*************************** End of file ****************************/
