/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.40                          *
*        Compiled Jun 22 2017, 10:13:26                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#define EXTERN extern
#include "stm32f4xx_hal.h"
#include "main.h"
#include "GuiData.h"

static void DeviceDescroptionSend(uint16_t device);
static void DeviceDescriptionDisp(uint16_t device);
static void DisplayConnectSettingMenu(int pos, uint16_t device, uint8_t flag);
static void DisplayConnectSetting(void);
static void DisplaySettingMenu(int page, int pos, int flag);
static void SettingMenuExec(int nPage, int nPos);
static void DisplaySetting(void);
static void SetupDeviceInfoValueDisp(void);
static void DisplayDeviceDisp(void);
static void SetInfoMenu(int menu, int pos, int count, int flag);

static char deviceDescription[MESSAGE_BUF_SIZE];

static void FactoryReset(void);
static void FactoryResetInitDisp(void);
static void DisplayDeviceDispValue(void);


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
static void DeviceDescroptionSend(uint16_t device)
{
	(void)sprintf(deviceDescription, "");
	uint16_t address;
	if(ConnectSetting[device-1].DeviceType == DEVICE_MLINK)
	{
		address = SETUP_READ_ADDR;
	}
	else
	if((ConnectSetting[device-1].DeviceType == DEVICE_ACB) || (ConnectSetting[device-1].DeviceType == DEVICE_MCCB))
	{
		address = 1;
	}
	else
	{
		return;
	}
	ModbusSendFrame(ConnectSetting[device-1].Address, HOLDING_REGISTER, address, SETUP_READ_LEN);
}

static void DeviceDescriptionDisp(uint16_t device)
{
//	GUI_SetBkColor(COLOR_MENU_NORMAL);
//	(void)GUI_SetFont(&GUI_Font20B_ASCII);
//	GUI_SetColor(COLOR_VALUE);
//
//	GUI_RECT rect2;
//	rect2.x0 = SETUP_VALUE_X0;
//	rect2.y0 = (SETTING_STARTY_LABEL + (SETTING_SUB_HEIGHT*INDEX_4));
//	rect2.x1 = SETUP_VALUE_X1;
////	rect2.y1 = (SETTING_STARTY_LABEL + (SETTING_SUB_HEIGHT*INDEX_5)) - INDEX_2;
//	rect2.y1 = rect2.y0 + SETTING_SUB_HEIGHT;
//
	uint16_t address = 1;
	if(ConnectSetting[device-1].DeviceType == DEVICE_MLINK)
	{
		address = SETUP_READ_ADDR;
	}
	char buf[MESSAGE_BUF_SIZE];
	ModbusGetString(address, INDEX_32, buf);

	if(strlen(buf) > INDEX_16)
	{
		buf[INDEX_16] = '.';
		buf[INDEX_17] = '.';
		buf[INDEX_18] = '.';
		buf[INDEX_19] = 0;
	}

	(void)sprintf(deviceDescription, "%s", buf);
//	GUI_ClearRectEx(&rect2);
//	GUI_DispStringInRect(buf, &rect2, GUI_TA_LEFT | GUI_TA_VCENTER);
}

void TerminateSet(void);

static void DisplayConnectSettingMenu(int pos, uint16_t device, uint8_t flag)
{
	int count = LINECOUNT_CONTENTS-1;

	GUI_SetBkColor(COLOR_MAIN_BG);
	(void)GUI_SetFont(&GUI_Font20_ASCII);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_LINE);

	if(flag)
	{
		GUI_ClearRect(X0_MAIN, Y0_FULL, X1_MAIN, Y1_MAIN);

		GUI_SetColor(COLOR_CONTENTS);
		GUI_FillRect(STARTX_CONTENTS, SETTING_STARTY_LABEL, (STARTX_CONTENTS + WIDTH_CONTENTS) - 1, (SETTING_STARTY_LABEL + (SETTING_SUB_HEIGHT * count )) - 1);
	}

	int y0 = SETTING_STARTY_LABEL;

	GUI_RECT rect;
	rect.x0 = SETUP_LABEL_X0;
	rect.y0 = SETTING_STARTY_LABEL;
	rect.x1 = SETUP_LABEL_X1;
	rect.y1 = (SETTING_STARTY_LABEL +  SETTING_SUB_HEIGHT) - 1;

	GUI_RECT rect2;
	rect2.x0 = SETUP_VALUE_X0;
	rect2.y0 = SETTING_STARTY_LABEL;
	rect2.x1 = SETUP_VALUE_X1;
	rect2.y1 = (SETTING_STARTY_LABEL + SETTING_SUB_HEIGHT) - 1;

	char buf[DEFAULT_BUF_SIZE];
	for(int i = 0 ; i < count; i++)
	{
		if(i == pos)
		{
			GUI_SetColor(COLOR_MENU_SELECTED);
		}
		else
		{
			GUI_SetColor(COLOR_MENU_NORMAL);
		}
		GUI_FillRect(STARTX_CONTENTS, y0, (STARTX_CONTENTS + INFO_MENU_WIDTH) - 1, (y0 + SETTING_SUB_HEIGHT) - 1);

		if(i == pos)
		{
//			(void)GUI_SetFont(&GUI_Font20B_ASCII);
			LanguageSelect(FONT20B);
			GUI_SetColor(COLOR_VALUE);
			GUI_SetBkColor(COLOR_MENU_SELECTED);
		}
		else
		{
//			(void)GUI_SetFont(&GUI_Font20_ASCII);
			LanguageSelect(FONT20);
			GUI_SetColor(COLOR_LABEL);
			GUI_SetBkColor(COLOR_MENU_NORMAL);
		}

		GUI_DispStringInRect(_acsetup_disp_conn_label_text[SettingValue[SETUP_LANGUAGE]][i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);

		(void)GUI_SetFont(&GUI_Font20B_ASCII);
		GUI_SetColor(COLOR_VALUE);
		if(i == INDEX_0)
		{
			(void)sprintf(buf, "%d", SettingValue[SETUP_DEVICE_COUNT]);
		}
		else
		if(i == INDEX_1)
		{
			(void)sprintf(buf, "%d", device);
		}
		else
		if(i == INDEX_2)
		{
			(void)sprintf(buf, "%03d", ConnectSetting[device-1].Address);
		}
		else
		if(i == INDEX_3)
		{
			if(ConnectSetting[device-1].DeviceType < DEVICE_NO)
			{
				(void)sprintf(buf, "%s", _acsetup_type[ConnectSetting[device-1].DeviceType]);
			}
			else
			{
				(void)sprintf(buf, "NotDefined");
			}
		}
		else
		if(i == INDEX_4)
		{
//			(void)GUI_SetFont(&GUI_Font16B_ASCII);
			(void)sprintf(buf, "%s", deviceDescription);
		}
		else {}
		GUI_DispStringInRect(buf, &rect2, GUI_TA_LEFT | GUI_TA_VCENTER);

		rect.y0 += SETTING_SUB_HEIGHT;
		rect.y1 += SETTING_SUB_HEIGHT;
		rect2.y0 += SETTING_SUB_HEIGHT;
		rect2.y1 += SETTING_SUB_HEIGHT;
		y0 += SETTING_SUB_HEIGHT + 1;
	}
}

static void DisplayConnectSetting(void)
{
	int nPos = 0;
	uint16_t device = 1;

	DisplayConnectSettingMenu(nPos, device, 1);
	DeviceDescroptionSend(device);
	while (1)
	{
		E_KEY key = GetKey();

		if(key == KEY_UP)
		{
			if(nPos > 0)
			{
				nPos--;
			}
			else
			{
				nPos = LINECOUNT_CONTENTS - INDEX_3;
			}
			DisplayConnectSettingMenu(nPos, device, 0);
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPos < (LINECOUNT_CONTENTS - INDEX_3))
			{
				nPos++;
			}
			else
			{
				nPos = 0;
			}
			DisplayConnectSettingMenu(nPos, device, 0);
		}
		else
		if(key == KEY_ENTER)
		{
			if(nPos == INDEX_0)
			{
				if(SettingInput(&SettingValue[SETUP_DEVICE_COUNT], 1, DEVICE_MAX,0) == TRUE)
				{
					for(int i = SettingValue[SETUP_DEVICE_COUNT]; i < DEVICE_MAX; i++)
					{
						ConnectSetting[i].DeviceType = DEVICE_NO;
						gFaultEventReaded[i] = 0;
					}
					FlashWrite();
					gDeviceCount = SettingValue[SETUP_DEVICE_COUNT];
				}
				if(device > SettingValue[SETUP_DEVICE_COUNT])
				{
					device = SettingValue[SETUP_DEVICE_COUNT];
					gFaultEventReaded[device-1] = 0;
					FlashWrite();
				}
			}
			else
			if(nPos == INDEX_1)
			{
				(void)SettingInput(&device, 1, SettingValue[SETUP_DEVICE_COUNT], 0);
				DeviceDescroptionSend(device);
			}
			else
			if(nPos == INDEX_2)
			{
				if(SettingInput(&ConnectSetting[device-1].Address, SETUP_DEVICE_ADDR_MIN, SETUP_DEVICE_ADDR_MAX, 0) == TRUE)
				{
					gFaultEventReaded[device-1] = 0;
					FlashWrite();
				}
				DeviceDescroptionSend(device);
			}
			else
			if(nPos == INDEX_3)
			{
// PRQA S 0310 1
				if(SettingInputString((uint16_t*)(&ConnectSetting[device-1].DeviceType), SETUP_TYPE_MAX, _acsetup_type, FALSE) == TRUE)
				{
					gFaultEventReaded[device-1] = 0;
					FlashWrite();
				}
				DeviceDescroptionSend(device);
			}
			else
			if(nPos == INDEX_4)
			{
				continue;
			}
			else {}
//			{
//				if(SettingInput(&ConnectSetting[device-1].Address, SETUP_DEVICE_ADDR_MIN, SETUP_DEVICE_ADDR_MAX) == TRUE)
//					FlashWrite();
//			}
			DisplayConnectSettingMenu(nPos, device, 1);
		}
		else
		if(key == DATA_RECV)
		{
			DeviceDescriptionDisp(device);
//			DisplayConnectSettingMenu(nPos, device, 1);
		}
		else
		if(key == KEY_CANCEL)
		{
			break;
		}
		else {}
	}
}

static void DisplaySettingMenu(int page, int pos, int flag)
{
	int count = LINECOUNT_CONTENTS-1;
	int offset = 0;
	int startY = SETTING_STARTY_LABEL + (page * SETTING_SUB_HEIGHT);

	GUI_SetBkColor(COLOR_MAIN_BG);
	(void)GUI_SetFont(&GUI_Font20_ASCII);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_LINE);

	if(flag)
	{
	  GUI_ClearRect(X0_MAIN, Y0_FULL, X1_MAIN, Y1_MAIN);

	  GUI_SetColor(COLOR_CONTENTS);
	  GUI_FillRect(STARTX_CONTENTS, startY, (STARTX_CONTENTS + WIDTH_CONTENTS) - 1, (startY + (SETTING_SUB_HEIGHT * count )) - 1);
	}

	int y0 = SETTING_STARTY_LABEL;

	GUI_RECT rect;
	rect.x0 = STARTX_LABEL;
	rect.y0 = SETTING_STARTY_LABEL;
	rect.x1 = (STARTX_LABEL +  WIDTH_LABEL) - 1;
	rect.y1 = (SETTING_STARTY_LABEL +  SETTING_SUB_HEIGHT) - 1;

	GUI_RECT rect2;
	rect2.x0 = SETUP_SETTING_X0;
	rect2.y0 = SETTING_STARTY_LABEL;
	rect2.x1 = SETUP_SETTING_X1;
	rect2.y1 = (SETTING_STARTY_LABEL + SETTING_SUB_HEIGHT) - 1;


	if(page == 1 || page == INDEX_2)
	{
		GUI_SetColor(GUI_WHITE);
		GUI_FillPolygon(UP_POINT, INDEX_3, SETUP_UPDOWN_X, y0);
		rect.y0 += SETTING_SUB_HEIGHT;
		rect.y1 += SETTING_SUB_HEIGHT;
		rect2.y0 += SETTING_SUB_HEIGHT;
		rect2.y1 += SETTING_SUB_HEIGHT;
		y0 += SETTING_SUB_HEIGHT + 1;
		if(page == INDEX_2)
		{
			count = INDEX_2;
			offset = INDEX_9;
		}
		else
		{
			count = INDEX_4;
			offset = INDEX_5;
		}
	}

	GUI_SetColor(COLOR_LABEL);
	(void)GUI_SetFont(&GUI_Font20_ASCII);
	PCF2127_readTime(1);

	for(int i = 0 ; i < count; i++)
	{
		if(i == pos)
		{
			GUI_SetColor(COLOR_MENU_SELECTED);
		}
		else
		{
			GUI_SetColor(COLOR_MENU_NORMAL);
		}
		GUI_FillRect(STARTX_CONTENTS, y0, (STARTX_CONTENTS + INFO_MENU_WIDTH) - 1, (y0 + SETTING_SUB_HEIGHT) - 1);

		if(i == pos)
		{
			LanguageSelect(FONT20B);
			GUI_SetColor(COLOR_VALUE);
			GUI_SetBkColor(COLOR_MENU_SELECTED);
		}
		else
		{
			LanguageSelect(FONT20);
			GUI_SetColor(COLOR_LABEL);
			GUI_SetBkColor(COLOR_MENU_NORMAL);
		}
		GUI_DispStringInRect(_acsetup_disp_setting_label_text[SettingValue[SETUP_LANGUAGE]][offset + i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		LanguageSelect(FONT20B);
		GUI_SetColor(COLOR_VALUE);

		int index = offset + i;
		char buf[MESSAGE_BUF_SIZE];

		if(index == INDEX_0)
		{
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], gDateTime.Year, gDateTime.Month, gDateTime.Day, gDateTime.Hour, gDateTime.Min, gDateTime.Sec);
		}
		else
		if(index == INDEX_1)
		{
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], SettingValue[SETUP_BRIGHTNESS]);
		}
		else
		if(index == INDEX_2)
		{
			if(SettingValue[SETUP_SAVING_MODE] == 0)
			{
				(void)sprintf(buf, _acsetup_disp_setting_value_text_not[SettingValue[SETUP_LANGUAGE]][index], _acNotUsed[SettingValue[SETUP_LANGUAGE]]);
			}
			else
			{
				(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], SettingValue[SETUP_SAVING_MODE]);
			}
		}
		else
		if(index == INDEX_3)
		{
			if(SettingValue[SETUP_SCREEN_SWITCHING] == 0)
			{
				(void)sprintf(buf, _acsetup_disp_setting_value_text_not[SettingValue[SETUP_LANGUAGE]][index], _acNotUsed[SettingValue[SETUP_LANGUAGE]]);
			}
			else
			{
				(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], SettingValue[SETUP_SCREEN_SWITCHING]);
			}
		}
		else
		if(index == INDEX_4)
		{
			if(SettingValue[SETUP_RETURN_TO_SCREEN] == 0)
			{
				(void)sprintf(buf, _acsetup_disp_setting_value_text_not[SettingValue[SETUP_LANGUAGE]][index], _acNotUsed[SettingValue[SETUP_LANGUAGE]]);
			}
			else
			{
				(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], SettingValue[SETUP_RETURN_TO_SCREEN]);
			}
		}
/*		else
		if(index == INDEX_5)
		{
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], _acsetup_language[SettingValue[SETUP_LANGUAGE]]);
			if(SettingValue[SETUP_LANGUAGE] == CHINESE)
			{
				(void)GUI_SetFont(&GUI_FontLSFont20n_);
			}
			else
			if(SettingValue[SETUP_LANGUAGE] == RUSSIAN)
			{
				(void)GUI_SetFont(&GUI_Fontcyrillic20_20x20);
			}
			else
			{
				(void)GUI_SetFont(&GUI_Font20B_ASCII);
			}
		}
*/		else
		if(index == INDEX_5)
		{
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index]);
		}
		else
		if(index == INDEX_6)
		{
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], _acsetup_speed[SettingValue[SETUP_SPEED]]);
		}
		else
		if(index == INDEX_7)
		{
			if(SettingValue[SETUP_TERM1_USE] != 1)
			{
				SettingValue[SETUP_TERM1_USE] = 0;
			}
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], _aconoff_text[SettingValue[SETUP_LANGUAGE]][SettingValue[SETUP_TERM1_USE]]);
		}
		else
		if(index == INDEX_8)
		{
			if(SettingValue[SETUP_TERM2_USE] != 1)
			{
				SettingValue[SETUP_TERM2_USE] = 0;
			}
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], _aconoff_text[SettingValue[SETUP_LANGUAGE]][SettingValue[SETUP_TERM2_USE]]);
		}
		else
		if(index == INDEX_9)
		{
			if(SettingValue[SETUP_GATEWAY_USE] != 1)
			{
				SettingValue[SETUP_GATEWAY_USE] = 0;
			}
			(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][index], _acsetup_gateway_use[SettingValue[SETUP_LANGUAGE]][SettingValue[SETUP_GATEWAY_USE]]);
		}
		else
		{
			buf[0] = 0;
		}
		GUI_DispStringInRect(buf, &rect2, GUI_TA_LEFT | GUI_TA_VCENTER);

		printf("(%d,%d %d,%d) %s\n", rect2.x0, rect2.y0,rect2.x1, rect2.y1, buf);

//		GUI_DispStringInRect(_acsetup_disp_setting_value_text[offset + i], &rect2, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += SETTING_SUB_HEIGHT;
		rect.y1 += SETTING_SUB_HEIGHT;
		rect2.y0 += SETTING_SUB_HEIGHT;
		rect2.y1 += SETTING_SUB_HEIGHT;
		y0 += SETTING_SUB_HEIGHT + 1;
	}
	if(page == 0 || page == INDEX_1)
	{
	  GUI_SetColor(GUI_WHITE);
	  GUI_FillPolygon(DOWN_POINT, INDEX_3, SETUP_UPDOWN_X, y0);
	}
}

static void FactoryResetInitDisp(void)
{
	GUI_RECT rect;

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_MENU_SELECTED);
	GUI_SetBkColor(COLOR_MENU_NORMAL);

	GUI_ClearRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);
	GUI_DrawRect(POPUP_WINDOW_X0, POPUP_WINDOW_Y0, POPUP_WINDOW_X1, POPUP_WINDOW_Y1);

	GUI_SetColor(SELECTED_TEXT_COLOR);
	LanguageSelect(FONT24);
	rect.x0 = CONTROL_MSG_X0 - INDEX_20;
	rect.y0 = CONTROL_MSG_Y0;
	rect.x1 = CONTROL_MSG_X1 + INDEX_20;
	rect.y1 = CONTROL_MSG_Y1;
	GUI_DispStringInRect(_aFactoryReset_confirm_text[SettingValue[SETUP_LANGUAGE]], &rect, GUI_TA_HCENTER | GUI_TA_VCENTER);

	MLinkButtonDisp(CONTROL_BUTTON_NOSELECT);
}

static void FactoryReset(void)
{
	int flagBreak = FALSE;
	int nPos = 0;
	char password[CONTROL_PASSWORD_DIGIT+1];

	(void)sprintf(password, "0000");
	FactoryResetInitDisp();
	PasswordDisp(nPos, password[nPos]);

	while (1)
	{
		E_KEY key = GetKey();

		if(key == KEY_UP)
		{
			if(nPos < CONTROL_PASSWORD_DIGIT)
			{
				if(password[nPos] < '9')
				{
					password[nPos]++;
				}
				else
				{
					password[nPos] = '0';
				}
				PasswordDisp(nPos, password[nPos]);
			}
			else
			if(nPos == (CONTROL_PASSWORD_DIGIT + 1))
			{
				MLinkButtonDisp(CONTROL_BUTTON_OK);
				nPos = CONTROL_PASSWORD_DIGIT;
			}
			else {}
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPos < CONTROL_PASSWORD_DIGIT)
			{
				if(password[nPos] > '0')
				{
					password[nPos]--;
				}
				else
				{
					password[nPos] = '9';
				}
				PasswordDisp(nPos, password[nPos]);
			}
			else
			if(nPos == CONTROL_PASSWORD_DIGIT)
			{
				MLinkButtonDisp(CONTROL_BUTTON_CANCEL);
				nPos = CONTROL_PASSWORD_DIGIT + 1;
			}
			else {}
		}
		else
		if(key == KEY_ENTER)
		{
			if(nPos < CONTROL_PASSWORD_DIGIT)
			{
				nPos++;
				PasswordDisp(nPos, password[nPos]);
				if(nPos == CONTROL_PASSWORD_DIGIT)
				{
					MLinkButtonDisp(CONTROL_BUTTON_OK);
				}
			}
			else
			if(nPos == CONTROL_PASSWORD_DIGIT)	// OK 이면
			{
				uint16_t  iPassword = atoi(password);
				if(iPassword != SettingValue[SETUP_PASSWORD])
				{
				   if(QuestionMessage() == FALSE)
				   {
						flagBreak = TRUE;
				   }
					nPos = 0;
					FactoryResetInitDisp();
					PasswordDisp(nPos, password[nPos]);
					MLinkButtonDisp(CONTROL_BUTTON_NOSELECT);
				}
				else
				{
					int nSpeed = SettingValue[SETUP_SPEED];
					for(int i = 0; i < DEVICE_MAX; i++)
					{
						gFaultEventReaded[i] = 0;
						ConnectSetting[i].DeviceType = DEVICE_NO;
						ConnectSetting[i].Address = i + 1;
						gCommStatus[i] = COMM_ERROR;
					}
					for(int i = 0; i < SETUP_COUNT; i++)
					{
						SettingValue[i] = DefaultSettingValue[i];
					}
					FlashWrite();
					flagBreak = TRUE;
					gDeviceCount = 1;
					if(SettingValue[SETUP_SPEED] != nSpeed)
					{
						MX_USART1_UART_Init();
						MX_USART2_UART_Init();
					}
					BacklightBrghtness(SettingValue[SETUP_BRIGHTNESS], FALSE);
				}
			}
			else
			if(nPos == (CONTROL_PASSWORD_DIGIT + 1))	// Cancel 이면
			{
				flagBreak = TRUE;
			}
			else {}
		}
		else
		if(key == KEY_CANCEL)
		{
			flagBreak = TRUE;
		}
		else {}

		if(flagBreak == TRUE)
		{
			break;
		}
	}
}

static void SettingMenuExec(int nPage, int nPos)
{
	if(nPage == INDEX_0)
	{
		if(nPos == INDEX_0)
		{
			gbSettingTime = TRUE;
			SettingTime();
			gbSettingTime = FALSE;
		}
		else
		if(nPos == INDEX_1)
		{
			if(SettingInput(&SettingValue[SETUP_BRIGHTNESS], SETUP_BRIGHT_MIN, SETUP_BRIGHT_MAX, 0) == TRUE)
			{
				FlashWrite();
				BacklightBrghtness(SettingValue[SETUP_BRIGHTNESS], FALSE);
			}
		}
		else
		if(nPos == INDEX_2)
		{
			if(SettingInput(&SettingValue[SETUP_SAVING_MODE], SETUP_SAVING_MIN, SETUP_SAVING_MAX, 1) == TRUE)
			{
				uint32_t timer = HAL_GetTick();
				gSavingModeCounter = timer + (SettingValue[SETUP_SAVING_MODE] * THOUSAND);
				FlashWrite();
			}
		}
		else
		if(nPos == INDEX_3)
		{
			if(SettingInput(&SettingValue[SETUP_SCREEN_SWITCHING], SETUP_SWITCHING_MIN, SETUP_SWITCHING_MAX, 1) == TRUE)
			{
				uint32_t timer = HAL_GetTick();
				gScreenSwitchingCounter = timer + (SettingValue[SETUP_SCREEN_SWITCHING] * THOUSAND);
				FlashWrite();
			}
		}
		else
		if(nPos == INDEX_4)
		{
			if(SettingInput(&SettingValue[SETUP_RETURN_TO_SCREEN], SETUP_RETURN_TO_MIN, SETUP_RETURN_TO_MAX, 1) == TRUE)
			{
				uint32_t timer = HAL_GetTick();
				gReturnToScreen = timer + (SettingValue[SETUP_RETURN_TO_SCREEN] * THOUSAND);
				FlashWrite();
			}
		}
		else {}
	}
	else
	if(nPage == INDEX_1)
	{
/*		if(nPos == INDEX_0)
		{
			if(SettingInputString(&SettingValue[SETUP_LANGUAGE], SETUP_LANGUAGE_INPUT_MAX, _acsetup_language, TRUE) == TRUE)
			{
				FlashWrite();
			}
		}
		else
*/		if(nPos == INDEX_0)
		{
			if(PasswordChange() == TRUE)
			{
				FlashWrite();
			}
		}
		else
		if(nPos == INDEX_1)
		{
			if(SettingInputString(&SettingValue[SETUP_SPEED], SETUP_SPEED_MAX, _acsetup_speed, FALSE) == TRUE)
			{
				FlashWrite();
				MX_USART1_UART_Init();
				MX_USART2_UART_Init();
			}
		}
		else
		if(nPos == INDEX_2)
		{
			if(SettingInputString(&SettingValue[SETUP_TERM1_USE], STATUS_COUNT, _aconoff_text[SettingValue[SETUP_LANGUAGE]], FALSE) == TRUE)
			{
				TerminateSet();
				FlashWrite();
			}
		}
		else
		if(nPos == INDEX_3)
		{
			if(SettingInputString(&SettingValue[SETUP_TERM2_USE], STATUS_COUNT, _aconoff_text[SettingValue[SETUP_LANGUAGE]], FALSE) == TRUE)
			{
				TerminateSet();
				FlashWrite();
			}
		}
		else {}
	}
	else
	if(nPage == INDEX_2)
	{
		if(nPos == INDEX_0)
		{
			if(SettingInputString(&SettingValue[SETUP_GATEWAY_USE], SETUP_GATEWAY_USE_MAX, _acsetup_gateway_use[SettingValue[SETUP_LANGUAGE]], FALSE) == TRUE)
			{
				FlashWrite();
			}
		}
		else
		if(nPos == INDEX_1)
		{
			FactoryReset();
		}
		else {}
	}
	else {}
}

static void DisplaySetting(void)
{
	int nPage = 0;
	int nPos = 0;
	DisplaySettingMenu(nPage, nPos, 1);
	while (1)
	{
		E_KEY key = GetKey();

		if(key == SECOND_TIMER)
		{
			// (void)printf("SECOND_TIMER\n\n\n\n");
			if(nPage == 0)
			{
				PCF2127_readTime(1);
				if(nPos == 0)
				{
					GUI_SetColor(COLOR_MENU_SELECTED);
				}
				else
				{
					GUI_SetColor(COLOR_MENU_NORMAL);
				}
//				GUI_FillRect(STARTX_CONTENTS, STARTY_CONTENTS, STARTX_CONTENTS + INFO_MENU_WIDTH - 1, STARTY_CONTENTS + HEIGHT_LABEL - 1);

				if(nPos == 0)
				{
					GUI_SetColor(COLOR_VALUE);
					GUI_SetBkColor(COLOR_MENU_SELECTED);
				}
				else
				{
					GUI_SetColor(COLOR_LABEL);
					GUI_SetBkColor(COLOR_MENU_NORMAL);
				}
				LanguageSelect(FONT20B);
				GUI_SetColor(COLOR_VALUE);

				char buf[MESSAGE_BUF_SIZE];

				(void)sprintf(buf, _acsetup_disp_setting_value_text[SettingValue[SETUP_LANGUAGE]][0], gDateTime.Year, gDateTime.Month, gDateTime.Day, gDateTime.Hour, gDateTime.Min, gDateTime.Sec);
				GUI_RECT rect2;
				rect2.x0 = SETUP_SETTING_X0;
				rect2.y0 = SETTING_STARTY_LABEL;
				rect2.x1 = SETUP_SETTING_X1;
				rect2.y1 = (SETTING_STARTY_LABEL + SETTING_SUB_HEIGHT) - 1;

				GUI_DispStringInRect(buf, &rect2, GUI_TA_LEFT | GUI_TA_VCENTER);
			}
		}
		else
		if(key == KEY_UP)
		{
			if(nPage == 0)
			{
				if(nPos > 0)
				{
					nPos--;
					DisplaySettingMenu(nPage, nPos, 0);
				}
				else
				{
					nPage = 2;
					nPos = INDEX_1;
					DisplaySettingMenu(nPage, nPos, 1);
				}
			}
			else
			if(nPage == 1)
			{
				if(nPos > 0)
				{
					nPos--;
					DisplaySettingMenu(nPage, nPos, 0);
				}
				else
//				if(nPos == 1)
				{
					nPos = INDEX_4;
					nPage = 0;
					DisplaySettingMenu(nPage, nPos, 1);
				}
			}
			else
			if(nPage == INDEX_2)
			{
				if(nPos > 0)
				{
					nPos--;
					DisplaySettingMenu(nPage, nPos, 0);
				}
				else
//				if(nPos == 1)
				{
					nPos = INDEX_3;
					nPage = 1;
					DisplaySettingMenu(nPage, nPos, 1);
				}
			}
			else {}
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPage == 0)
			{
				if(nPos < INDEX_4)
				{
					nPos++;
					DisplaySettingMenu(nPage, nPos, 0);
				}
				else
				if(nPos == INDEX_4)
				{
					nPage = 1;
					nPos = 0;
					DisplaySettingMenu(nPage, nPos, 1);
				}
				else {}
			}
			else
			if(nPage == 1)
			{
				if(nPos < INDEX_3)
				{
					nPos++;
					DisplaySettingMenu(nPage, nPos, 0);
				}
				else
				if(nPos == INDEX_3)
				{
					nPos = 0;
					nPage = INDEX_2;
					DisplaySettingMenu(nPage, nPos, 1);
				}
				else {}
			}
			else
			if(nPage == INDEX_2)
			{
				if(nPos < INDEX_1)
				{
					nPos++;
					DisplaySettingMenu(nPage, nPos, 0);
				}
				else
				if(nPos == INDEX_1)
				{
					nPos = 0;
					nPage = 0;
					DisplaySettingMenu(nPage, nPos, 1);
				}
				else {}
			}
			else {}
		}
		else
		if(key == KEY_ENTER)
		{
			SettingMenuExec(nPage, nPos);
			DisplaySettingMenu(nPage, nPos, 1);
		}
		else
		if(key == KEY_CANCEL)
		{
			break;
		}
		else {}
	}
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       Createstatus_window
*/

static void SetupDeviceInfoValueDisp(void)
{

	GUI_SetColor(COLOR_VALUE);
	GUI_RECT rect;
	rect.x0 = SETTING_STARTX_LABEL;
	rect.y0 = SETTING_STARTY_LABEL;
	rect.x1 = (STARTX_VALUE + WIDTH_VALUE) - 1;
	rect.y1 = (SETTING_STARTY_LABEL + SETTING_SUB_HEIGHT) - 1;
	(void)GUI_SetFont(&GUI_Font20B_ASCII);
	for(int i = 0 ; i < LINECOUNT_CONTENTS; i++)
	{
		if(i == INDEX_5)
		{
			LanguageSelect(FONT20B);
			GUI_SetColor(COLOR_VALUE);
			uint16_t status = RTCBatteryStatus();
			if(status)
			{
				GUI_SetColor(COLOR_WARNING);
				GUI_DispStringInRect(_acbat_status[SettingValue[SETUP_LANGUAGE]][1], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
			}
			else
			{
				GUI_DispStringInRect(_acbat_status[SettingValue[SETUP_LANGUAGE]][0], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
			}
		}
		else
		{
			if( i == INDEX_2)
			{
				GUI_DispStringInRect(_acHardwareVersion, &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
			}
			else
			{
				GUI_DispStringInRect(_acinfo_value_text[i], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
			}
		}
		rect.y0 += SETTING_SUB_HEIGHT;
		rect.y1 += SETTING_SUB_HEIGHT;
	}
}

static void DisplayDeviceDispValue(void)
{
	int count = LINECOUNT_CONTENTS;


	GUI_SetBkColor(COLOR_MAIN_BG);
	(void)GUI_SetFont(&GUI_Font20_ASCII);

	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_LINE);

	GUI_ClearRect(X0_MAIN, Y0_FULL, X1_MAIN, Y1_MAIN);
	GUI_DrawRect(STARTX_CONTENTS, SETTING_STARTY_LABEL, (STARTX_CONTENTS + WIDTH_CONTENTS) - 1, (SETTING_STARTY_LABEL + (SETTING_SUB_HEIGHT * count )) - 1);


	for(int i = 0; i < (count-1); i++)
	{
		int y0 = SETTING_STARTY_LABEL + ((i + 1) * SETTING_SUB_HEIGHT);
		GUI_DrawHLine(y0, STARTX_CONTENTS+INDEX_2, (STARTX_CONTENTS + WIDTH_CONTENTS) - 1);
	}

	GUI_SetColor(COLOR_LABEL);
	GUI_RECT rect;
	rect.x0 = STARTX_LABEL;
	rect.y0 = SETTING_STARTY_LABEL;
	rect.x1 = (STARTX_LABEL +  WIDTH_LABEL) - 1;
	rect.y1 = (SETTING_STARTY_LABEL +  SETTING_SUB_HEIGHT)- 1;

//	(void)GUI_SetFont(&GUI_Font20_ASCII);
	LanguageSelect(FONT20);
	for(int i = 0 ; i < count; i++)
	{
		GUI_DispStringInRect(_acsetupinfo_label_text[SettingValue[SETUP_LANGUAGE]][i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += SETTING_SUB_HEIGHT;
		rect.y1 += SETTING_SUB_HEIGHT;
	}
	SetupDeviceInfoValueDisp();
}

static void DisplayDeviceDisp(void)
{
	DisplayDeviceDispValue();

	GUI_RECT rect;
	rect.x0 = STARTX_LABEL;
	rect.y0 = SETTING_STARTY_LABEL;
	rect.x1 = (STARTX_LABEL +  WIDTH_LABEL) - 1;
	rect.y1 = (SETTING_STARTY_LABEL +  SETTING_SUB_HEIGHT)- 1;
	while (1)
	{
		E_KEY key = GetKey();
		if(key == TIME_OUT)
		{
//			GUI_RECT rect;
			rect.x0 = SETTING_STARTX_LABEL;
			rect.y0 = SETTING_STARTY_LABEL + (SETTING_SUB_HEIGHT*INDEX_5)+1;
			rect.x1 = (STARTX_VALUE + WIDTH_VALUE) - 1;
			rect.y1 = (SETTING_STARTY_LABEL + (SETTING_SUB_HEIGHT*INDEX_6)) - INDEX_2;
			//(void)GUI_SetFont(&GUI_Font20B_ASCII);
			LanguageSelect(FONT20B);
			uint16_t status = RTCBatteryStatus();
			GUI_ClearRect(rect.x0, rect.y0, rect.x1, rect.y1);
			if(status)
			{
				GUI_SetColor(COLOR_WARNING);
				GUI_DispStringInRect(_acbat_status[SettingValue[SETUP_LANGUAGE]][1], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
			}
			else
			{
				GUI_SetColor(COLOR_VALUE);
				GUI_DispStringInRect(_acbat_status[SettingValue[SETUP_LANGUAGE]][0], &rect, GUI_TA_RIGHT | GUI_TA_VCENTER);
			}
		}
		else
		if(key == KEY_CANCEL)
		{
			break;
		}
		else {}
	}
}

static void SetInfoMenu(int menu, int pos, int count, int flag)
{
	GUI_SetBkColor(COLOR_MAIN_BG);

	if(flag)
	{
		GUI_ClearRect(X0_MAIN, Y0_FULL, X1_MAIN, Y1_MAIN);
	}
	GUI_RECT rect;
	rect.x0 = INFO_MENU_X0;
	rect.x1 = (INFO_MENU_X0 + INFO_MENU_WIDTH) - 1;
	rect.y0 = SETTING_STARTY_LABEL;
	rect.y1 = (SETTING_STARTY_LABEL + SEETING_HEIGHT_LABEL) - 1;

	int y0 = SETTING_STARTY_LABEL;
	for(int i = 0; i < count; i++)
	{
		if(i == pos)
		{
			GUI_SetColor(COLOR_MENU_SELECTED);
		}
		else
		{
			GUI_SetColor(COLOR_MENU_NORMAL);
		}
		GUI_FillRect(STARTX_CONTENTS, y0, (SETTING_STARTY_LABEL + INFO_MENU_WIDTH) - 1, (y0 + SEETING_HEIGHT_LABEL) - 1);

		if(i == pos)
		{
//			(void)GUI_SetFont(&GUI_Font24B_ASCII);
			LanguageSelect(FONT24B);
			GUI_SetColor(COLOR_VALUE);
			GUI_SetBkColor(COLOR_MENU_SELECTED);
		}
		else
		{
//			(void)GUI_SetFont(&GUI_Font24_ASCII);
			LanguageSelect(FONT24);
			GUI_SetColor(COLOR_LABEL);
			GUI_SetBkColor(COLOR_MENU_NORMAL);
		}

		GUI_DispStringInRect(_acinfo_menu_text[SettingValue[SETUP_LANGUAGE]][menu][i], &rect, GUI_TA_LEFT | GUI_TA_VCENTER);
		rect.y0 += SEETING_HEIGHT_LABEL + 1;
		rect.y1 += SEETING_HEIGHT_LABEL + 1;
		y0 += SEETING_HEIGHT_LABEL + 1;;
	}
}


// PRQA S 1503 1
E_SETUP_RETURN Setup(void)
{
	E_SETUP_RETURN ret = SETUP_NOCHANGED;
	int nPos = 0;

	SetInfoMenu(SETTING_MENU, nPos, SETTING_MENU_COUNT, 1);

	GUI_SetBkColor(COLOR_MAIN_BG);
	(void)GUI_SetPenSize(PENSIZE_LINE);
	GUI_SetColor(COLOR_LINE);

	g_nStatusNoUpdate = 1;

	E_DEVICE_TYPE deviceType	= ConnectSetting[gDeviceIndex].DeviceType;

	while (1)
    {
		E_KEY key = GetKey();

		if(key == KEY_UP)
		{
			if(nPos > 0)
			{
				nPos--;
			}
			else
			{
				nPos = SETTING_MENU_COUNT - 1;
			}
			SetInfoMenu(SETTING_MENU, nPos, SETTING_MENU_COUNT, 0);
		}
		else
		if(key == KEY_DOWN)
		{
			if(nPos < (SETTING_MENU_COUNT-1))
			{
				nPos++;
			}
			else
			{
				nPos = 0;
			}
			SetInfoMenu(SETTING_MENU, nPos, SETTING_MENU_COUNT, 0);
		}
		else
		if(key == KEY_ENTER)
		{
			if(nPos == INDEX_0)
			{
				DisplayDeviceDisp();
			}
			else
			if(nPos == INDEX_1)
			{
				DisplaySetting();
			}
			else
			if(nPos == INDEX_2)
			{
				DisplayConnectSetting();
			}
			else {}
			SetInfoMenu(SETTING_MENU, nPos, SETTING_MENU_COUNT, 1);
		}
		else
		if(key == KEY_CANCEL)
		{
			DispStatus();
			g_nStatusNoUpdate = 0;
			if(SettingValue[SETUP_DEVICE_COUNT] <= gDeviceIndex)
			{
				gDeviceIndex = SettingValue[SETUP_DEVICE_COUNT] - 1;
			}
			if(deviceType != ConnectSetting[gDeviceIndex].DeviceType)
			{
				ret = SETUP_CHANGED;
			}
			gCommOldStatus[gDeviceIndex] = -1;
			break;
		}
		else {}
	}
	g_bRecvAllDone = TRUE;
	CommTimerInit();
	return ret;
}
// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
